/*
 * deq_decoder.h - stable C ABI for deq dynamic decoder plugins.
 *
 * GENERATED by cbindgen from the deq-decoder-reference-plugin crate.
 * DO NOT EDIT BY HAND. Regenerate with:
 *   deq/deq_decoder_abi/reference_plugin/regenerate.sh
 * Source of truth: deq/deq_decoder_abi/src/{interface.rs,plugin.rs}.
 *
 * A decoder plugin is a shared library (.so/.dylib/.dll) exporting these
 * symbols. deq dlopens it, checks the ABI version, builds one decoder per
 * decoding hypergraph, and calls deq_decoder_decode once per shot in-process.
 * Only plain-old-data crosses the boundary; C++ plugins must not let
 * exceptions escape.
 *
 * Integer type convention (so the mix below is not surprising):
 *   - uint64_t  for problem-domain quantities that must have the same width on
 *     every build: vertex_num, edge_num, syndrome_size. These mirror deq's wire
 *     types and stay identical across a 32- vs 64-bit host.
 *   - size_t    for in-memory buffer lengths and capacities: edge_vertices_len,
 *     syndrome_len, out_cap, out_len. These are object sizes (sizeof/indexing),
 *     so the native C type is used; a plugin always shares the host's
 *     architecture, so size_t has the same width on both sides.
 *   - int32_t   for status codes: a fixed-width return is the correct choice for
 *     a binary contract (plain int has no guaranteed width).
 */

#ifndef DEQ_DECODER_H
#define DEQ_DECODER_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI revision; see [`deq_decoder_abi::ABI_VERSION`].
 */
#define DEQ_DECODER_ABI_VERSION 1

/**
 * decode succeeded; see [`deq_decoder_abi::STATUS_OK`].
 */
#define DEQ_DECODER_STATUS_OK 0

/**
 * output buffer too small; see [`deq_decoder_abi::STATUS_BUFFER_TOO_SMALL`].
 */
#define DEQ_DECODER_STATUS_BUFFER_TOO_SMALL 1

/**
 * generic recoverable error; see [`deq_decoder_abi::STATUS_ERROR`].
 */
#define DEQ_DECODER_STATUS_ERROR -1

/**
 * invalid argument; see [`deq_decoder_abi::STATUS_INVALID_ARG`].
 */
#define DEQ_DECODER_STATUS_INVALID_ARG -2

/**
 * plugin panicked, handle poisoned; see [`deq_decoder_abi::STATUS_PANIC`].
 */
#define DEQ_DECODER_STATUS_PANIC -3

/**
 * handle already poisoned; see [`deq_decoder_abi::STATUS_POISONED`].
 */
#define DEQ_DECODER_STATUS_POISONED -4

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t deq_decoder_abi_version(void);

/**
 * # Safety
 * See [`deq_decoder_abi::interface::CreateFn`].
 */
int32_t deq_decoder_create(uint64_t vertex_num,
                           uint64_t edge_num,
                           const double *edge_probs,
                           const uint64_t *edge_offsets,
                           const uint64_t *edge_vertices,
                           size_t edge_vertices_len,
                           const char *config_json,
                           void **out_handle);

/**
 * # Safety
 * See [`deq_decoder_abi::interface::DecodeFn`].
 */
int32_t deq_decoder_decode(void *handle,
                           uint64_t syndrome_size,
                           const uint8_t *syndrome_data,
                           size_t syndrome_len,
                           uint64_t *out_ptr,
                           size_t out_cap,
                           size_t *out_len);

/**
 * # Safety
 * See [`deq_decoder_abi::interface::DestroyFn`].
 */
void deq_decoder_destroy(void *handle);

/**
 * # Safety
 * See [`deq_decoder_abi::interface::LastErrorFn`].
 */
const char *deq_decoder_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DEQ_DECODER_H */
