// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BitMatrix {
    #[prost(uint64, tag = "1")]
    pub rows: u64,
    #[prost(uint64, tag = "2")]
    pub cols: u64,
    /// we use sparse representation by specifying the locations of 1s
    #[prost(uint64, repeated, tag = "3")]
    pub i: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "4")]
    pub j: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BitVector {
    #[prost(uint64, tag = "1")]
    pub size: u64,
    /// we use dense representation because outcomes are usually dense
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
