// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchExecuteRequest {
    #[prost(message, repeated, tag = "1")]
    pub instructions: ::prost::alloc::vec::Vec<super::super::jit::JitInstruction>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BatchExecuteResponse {
    /// assigned gids in the same order as the input instructions
    #[prost(uint64, repeated, tag = "1")]
    pub gids: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchOutcomes {
    #[prost(message, repeated, tag = "1")]
    pub outcomes: ::prost::alloc::vec::Vec<super::super::coordinator::Outcomes>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchReadouts {
    /// readouts in the same order as the input outcomes
    #[prost(message, repeated, tag = "1")]
    pub readouts: ::prost::alloc::vec::Vec<super::super::coordinator::Readouts>,
}
/// Generated client implementations.
#[cfg(feature = "cli")]
pub mod jit_controller_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct JitControllerClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl JitControllerClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> JitControllerClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> JitControllerClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            JitControllerClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// load the library, preferably offline (well before the circuit runs) but can
        /// also run online to enable the capability of very dynamic behaviors
        pub async fn load_library(
            &mut self,
            request: impl tonic::IntoRequest<super::super::super::jit::JitLibrary>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.controller.jit_controller.JitController/LoadLibrary",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.controller.jit_controller.JitController",
                        "LoadLibrary",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// remove certain gadgets, check models or error models to free up resources
        pub async fn unload(
            &mut self,
            request: impl tonic::IntoRequest<super::super::super::jit::UnloadJitLibrary>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.controller.jit_controller.JitController/Unload",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.controller.jit_controller.JitController",
                        "Unload",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// return the id of the new instruction (which creates an instance of a
        /// gadget, a check model or an error model)
        pub async fn execute(
            &mut self,
            request: impl tonic::IntoRequest<super::super::super::jit::JitInstruction>,
        ) -> std::result::Result<
            tonic::Response<super::super::super::coordinator::ExecuteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.controller.jit_controller.JitController/Execute",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.controller.jit_controller.JitController",
                        "Execute",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// execute multiple instructions in batch, respecting dependencies between
        /// them. all instructions must specify a non-zero gid. Dependencies (via
        /// connectors) are validated: referenced gids must either exist in this batch
        /// or have been previously executed. The entire batch is rejected if any
        /// validation fails.
        pub async fn batch_execute(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchExecuteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchExecuteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.controller.jit_controller.JitController/BatchExecute",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.controller.jit_controller.JitController",
                        "BatchExecute",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// input the measurement outcomes of a gadget and return the logical readouts.
        /// note that the readouts generally depend on adjacent gadgets' outcomes so
        /// it may not return immediately (unless the number of readouts are zero)
        pub async fn decode(
            &mut self,
            request: impl tonic::IntoRequest<super::super::super::coordinator::Outcomes>,
        ) -> std::result::Result<
            tonic::Response<super::super::super::coordinator::Readouts>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.controller.jit_controller.JitController/Decode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.controller.jit_controller.JitController",
                        "Decode",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// decode multiple gadgets concurrently. All decode operations run in
        /// parallel, which is critical for window decoding where earlier decodes may
        /// depend on later ones. Returns readouts in the same order as the input
        /// outcomes.
        pub async fn batch_decode(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchOutcomes>,
        ) -> std::result::Result<tonic::Response<super::BatchReadouts>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.controller.jit_controller.JitController/BatchDecode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.controller.jit_controller.JitController",
                        "BatchDecode",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// reset the system
        pub async fn reset(
            &mut self,
            request: impl tonic::IntoRequest<
                super::super::super::coordinator::ResetRequest,
            >,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.controller.jit_controller.JitController/Reset",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.controller.jit_controller.JitController",
                        "Reset",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod jit_controller_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with JitControllerServer.
    #[async_trait]
    pub trait JitController: std::marker::Send + std::marker::Sync + 'static {
        /// load the library, preferably offline (well before the circuit runs) but can
        /// also run online to enable the capability of very dynamic behaviors
        async fn load_library(
            &self,
            request: tonic::Request<super::super::super::jit::JitLibrary>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        /// remove certain gadgets, check models or error models to free up resources
        async fn unload(
            &self,
            request: tonic::Request<super::super::super::jit::UnloadJitLibrary>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        /// return the id of the new instruction (which creates an instance of a
        /// gadget, a check model or an error model)
        async fn execute(
            &self,
            request: tonic::Request<super::super::super::jit::JitInstruction>,
        ) -> std::result::Result<
            tonic::Response<super::super::super::coordinator::ExecuteResponse>,
            tonic::Status,
        >;
        /// execute multiple instructions in batch, respecting dependencies between
        /// them. all instructions must specify a non-zero gid. Dependencies (via
        /// connectors) are validated: referenced gids must either exist in this batch
        /// or have been previously executed. The entire batch is rejected if any
        /// validation fails.
        async fn batch_execute(
            &self,
            request: tonic::Request<super::BatchExecuteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchExecuteResponse>,
            tonic::Status,
        >;
        /// input the measurement outcomes of a gadget and return the logical readouts.
        /// note that the readouts generally depend on adjacent gadgets' outcomes so
        /// it may not return immediately (unless the number of readouts are zero)
        async fn decode(
            &self,
            request: tonic::Request<super::super::super::coordinator::Outcomes>,
        ) -> std::result::Result<
            tonic::Response<super::super::super::coordinator::Readouts>,
            tonic::Status,
        >;
        /// decode multiple gadgets concurrently. All decode operations run in
        /// parallel, which is critical for window decoding where earlier decodes may
        /// depend on later ones. Returns readouts in the same order as the input
        /// outcomes.
        async fn batch_decode(
            &self,
            request: tonic::Request<super::BatchOutcomes>,
        ) -> std::result::Result<tonic::Response<super::BatchReadouts>, tonic::Status>;
        /// reset the system
        async fn reset(
            &self,
            request: tonic::Request<super::super::super::coordinator::ResetRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct JitControllerServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> JitControllerServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for JitControllerServer<T>
    where
        T: JitController,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/deq.controller.jit_controller.JitController/LoadLibrary" => {
                    #[allow(non_camel_case_types)]
                    struct LoadLibrarySvc<T: JitController>(pub Arc<T>);
                    impl<
                        T: JitController,
                    > tonic::server::UnaryService<super::super::super::jit::JitLibrary>
                    for LoadLibrarySvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::super::super::jit::JitLibrary>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JitController>::load_library(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoadLibrarySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.controller.jit_controller.JitController/Unload" => {
                    #[allow(non_camel_case_types)]
                    struct UnloadSvc<T: JitController>(pub Arc<T>);
                    impl<
                        T: JitController,
                    > tonic::server::UnaryService<
                        super::super::super::jit::UnloadJitLibrary,
                    > for UnloadSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::super::super::jit::UnloadJitLibrary,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JitController>::unload(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnloadSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.controller.jit_controller.JitController/Execute" => {
                    #[allow(non_camel_case_types)]
                    struct ExecuteSvc<T: JitController>(pub Arc<T>);
                    impl<
                        T: JitController,
                    > tonic::server::UnaryService<
                        super::super::super::jit::JitInstruction,
                    > for ExecuteSvc<T> {
                        type Response = super::super::super::coordinator::ExecuteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::super::super::jit::JitInstruction,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JitController>::execute(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExecuteSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.controller.jit_controller.JitController/BatchExecute" => {
                    #[allow(non_camel_case_types)]
                    struct BatchExecuteSvc<T: JitController>(pub Arc<T>);
                    impl<
                        T: JitController,
                    > tonic::server::UnaryService<super::BatchExecuteRequest>
                    for BatchExecuteSvc<T> {
                        type Response = super::BatchExecuteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BatchExecuteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JitController>::batch_execute(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BatchExecuteSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.controller.jit_controller.JitController/Decode" => {
                    #[allow(non_camel_case_types)]
                    struct DecodeSvc<T: JitController>(pub Arc<T>);
                    impl<
                        T: JitController,
                    > tonic::server::UnaryService<
                        super::super::super::coordinator::Outcomes,
                    > for DecodeSvc<T> {
                        type Response = super::super::super::coordinator::Readouts;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::super::super::coordinator::Outcomes,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JitController>::decode(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DecodeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.controller.jit_controller.JitController/BatchDecode" => {
                    #[allow(non_camel_case_types)]
                    struct BatchDecodeSvc<T: JitController>(pub Arc<T>);
                    impl<
                        T: JitController,
                    > tonic::server::UnaryService<super::BatchOutcomes>
                    for BatchDecodeSvc<T> {
                        type Response = super::BatchReadouts;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BatchOutcomes>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JitController>::batch_decode(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BatchDecodeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.controller.jit_controller.JitController/Reset" => {
                    #[allow(non_camel_case_types)]
                    struct ResetSvc<T: JitController>(pub Arc<T>);
                    impl<
                        T: JitController,
                    > tonic::server::UnaryService<
                        super::super::super::coordinator::ResetRequest,
                    > for ResetSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::super::super::coordinator::ResetRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JitController>::reset(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ResetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for JitControllerServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "deq.controller.jit_controller.JitController";
    impl<T> tonic::server::NamedService for JitControllerServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
