// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpanRecord {
    #[prost(uint64, tag = "1")]
    pub begin_time_unix_ns: u64,
    #[prost(uint64, tag = "2")]
    pub duration_ns: u64,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub properties: ::prost::alloc::vec::Vec<Property>,
    #[prost(message, repeated, tag = "5")]
    pub events: ::prost::alloc::vec::Vec<EventRecord>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Property {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventRecord {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub timestamp_unix_ns: u64,
    #[prost(message, repeated, tag = "3")]
    pub properties: ::prost::alloc::vec::Vec<Property>,
    #[prost(uint64, tag = "4")]
    pub delta_ns: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TraceFile {
    #[prost(message, repeated, tag = "1")]
    pub spans: ::prost::alloc::vec::Vec<SpanRecord>,
}
