// This file is @generated by prost-build.
/// One sampled shot from a simulator.
///
///
/// Carries only the flat physical-measurement record. Callers that want
/// per-gadget chunks can slice `outcomes` themselves using the
/// per-gadget measurement counts from the JIT library — the
/// : class:`deq.runtime.Sampler` wrapper exposes a `split_outcomes`
///   helper and a `partition` property for that.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShotSample {
    #[prost(message, optional, tag = "1")]
    pub outcomes: ::core::option::Option<super::util::BitVector>,
}
