// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DecoderCapabilities {
    #[prost(enumeration = "DecoderFeature", repeated, tag = "1")]
    pub features: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResetRequest {
    /// by default keep all the hypergraphs intact
    #[prost(bool, tag = "1")]
    pub reset_hypergraphs: bool,
    /// other custom things
    #[prost(string, tag = "200")]
    pub custom: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecodingProblem {
    #[prost(message, optional, tag = "1")]
    pub hypergraph: ::core::option::Option<DecodingHypergraph>,
    #[prost(message, optional, tag = "2")]
    pub syndrome: ::core::option::Option<super::super::util::BitVector>,
    /// Optional loss-aware extension. Present only when atom losses are observed
    /// for this shot; absent otherwise.
    #[prost(message, optional, tag = "3")]
    pub loss: ::core::option::Option<LossInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoadHypergraphResponse {
    /// hypergraph id assigned by the decoder service
    #[prost(uint64, tag = "1")]
    pub hid: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoadedDecodingProblem {
    #[prost(uint64, tag = "1")]
    pub hid: u64,
    #[prost(message, optional, tag = "2")]
    pub syndrome: ::core::option::Option<super::super::util::BitVector>,
    /// Optional per-shot prior overrides, applied to this decode only. The loaded
    /// hypergraph is left unchanged, so a subsequent decode on the same `hid` sees
    /// the priors it was loaded with.
    #[prost(message, repeated, tag = "3")]
    pub reweights: ::prost::alloc::vec::Vec<EdgeReweight>,
    /// Optional loss-aware extension. Present only when atom losses are observed
    /// for this shot; absent otherwise.
    #[prost(message, optional, tag = "4")]
    pub loss: ::core::option::Option<LossInfo>,
}
/// Replaces the prior of one hyperedge, addressed by its index in the loaded
/// hypergraph. The probability is *assigned*, not combined: it may raise or lower
/// the loaded prior. Each edge may appear at most once in a request.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EdgeReweight {
    #[prost(uint64, tag = "1")]
    pub edge: u64,
    #[prost(double, tag = "2")]
    pub probability: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParityFactor {
    #[prost(uint64, repeated, tag = "1")]
    pub subgraph: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecodingHypergraph {
    #[prost(uint64, tag = "1")]
    pub vertex_num: u64,
    #[prost(message, repeated, tag = "2")]
    pub hyperedges: ::prost::alloc::vec::Vec<Hyperedge>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hyperedge {
    #[prost(uint64, repeated, tag = "1")]
    pub vertices: ::prost::alloc::vec::Vec<u64>,
    /// we use probability instead of weight here to make it more intuitive
    /// and easier to manipulate, e.g., updating the soft information
    #[prost(double, tag = "2")]
    pub probability: f64,
}
/// The observed atom-loss graph for one shot, projected onto the decoding
/// problem's own indices. Enforcing exclusivity is a decoder policy, expressed
/// through `LossSite.children`. A reweighting strategy can instead flatten the
/// sites into ordinary reweighted hyperedges for an unmodified black-box decoder.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LossInfo {
    /// One entry per possible loss site. The runtime has already filtered these to
    /// the sites consistent with the observed loss-resolving readouts (herald
    /// folding), so per-site heralds are not exposed to the decoder. That is, we
    /// guarantee that at least one of the readout is loss and none of them are non-loss
    /// (those readouts outside of the decoding window are not considered)
    #[prost(message, repeated, tag = "1")]
    pub sites: ::prost::alloc::vec::Vec<LossSite>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LossSite {
    /// Hyperedge indices (into DecodingHypergraph.hyperedges) for the SOURCE
    /// generators at the loss location. Along a parent/child chain (one atom) at
    /// most one site's source is the true start -- the exclusivity because a qubit
    /// cannot lose twice.
    #[prost(uint64, repeated, tag = "1")]
    pub source_edges: ::prost::alloc::vec::Vec<u64>,
    /// Hyperedge indices for the CONTINUATION generators (the loss propagated
    /// forward). Not mutually exclusive; they accompany whichever start reaches
    /// them.
    #[prost(uint64, repeated, tag = "2")]
    pub continuation_edges: ::prost::alloc::vec::Vec<u64>,
    /// Forward parent -> child links (same atom, lost later): indices into
    /// LossInfo.sites.
    #[prost(uint64, repeated, tag = "3")]
    pub children: ::prost::alloc::vec::Vec<u64>,
    /// Declared LOSS_ERROR probability of the loss starting at this site, or 0 for
    /// a continuation site fixed by a parent in another gadget.
    #[prost(double, tag = "4")]
    pub probability: f64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DecoderFeature {
    Unspecified = 0,
    Reweights = 1,
    Loss = 2,
}
impl DecoderFeature {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DECODER_FEATURE_UNSPECIFIED",
            Self::Reweights => "DECODER_FEATURE_REWEIGHTS",
            Self::Loss => "DECODER_FEATURE_LOSS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DECODER_FEATURE_UNSPECIFIED" => Some(Self::Unspecified),
            "DECODER_FEATURE_REWEIGHTS" => Some(Self::Reweights),
            "DECODER_FEATURE_LOSS" => Some(Self::Loss),
            _ => None,
        }
    }
}
/// Generated client implementations.
#[cfg(feature = "cli")]
pub mod black_box_decoder_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct BlackBoxDecoderClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BlackBoxDecoderClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BlackBoxDecoderClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BlackBoxDecoderClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BlackBoxDecoderClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Report optional request fields this decoder can consume. Advertising
        /// multiple features means they may be used together in one decode request.
        pub async fn get_capabilities(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<
            tonic::Response<super::DecoderCapabilities>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.decoder.blackbox_decoder.BlackBoxDecoder/GetCapabilities",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.decoder.blackbox_decoder.BlackBoxDecoder",
                        "GetCapabilities",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// calling this service is in general inefficient because it has to process
        /// the entire decoding hypergraph during runtime. Consider using preloaded
        /// decoder instances like the rpc interfaces followed
        pub async fn decode(
            &mut self,
            request: impl tonic::IntoRequest<super::DecodingProblem>,
        ) -> std::result::Result<tonic::Response<super::ParityFactor>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.decoder.blackbox_decoder.BlackBoxDecoder/Decode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.decoder.blackbox_decoder.BlackBoxDecoder",
                        "Decode",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// load a decoding hypergraph into the decoder service so that the runtime
        /// decoding can simply decode using the existing instances
        pub async fn load_hypergraph(
            &mut self,
            request: impl tonic::IntoRequest<super::DecodingHypergraph>,
        ) -> std::result::Result<
            tonic::Response<super::LoadHypergraphResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.decoder.blackbox_decoder.BlackBoxDecoder/LoadHypergraph",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.decoder.blackbox_decoder.BlackBoxDecoder",
                        "LoadHypergraph",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// decode using a preloaded hypergraph instance
        pub async fn decode_loaded(
            &mut self,
            request: impl tonic::IntoRequest<super::LoadedDecodingProblem>,
        ) -> std::result::Result<tonic::Response<super::ParityFactor>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.decoder.blackbox_decoder.BlackBoxDecoder/DecodeLoaded",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.decoder.blackbox_decoder.BlackBoxDecoder",
                        "DecodeLoaded",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// remove all loaded hypergraph instances
        pub async fn reset(
            &mut self,
            request: impl tonic::IntoRequest<super::ResetRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.decoder.blackbox_decoder.BlackBoxDecoder/Reset",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "deq.decoder.blackbox_decoder.BlackBoxDecoder",
                        "Reset",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod black_box_decoder_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BlackBoxDecoderServer.
    #[async_trait]
    pub trait BlackBoxDecoder: std::marker::Send + std::marker::Sync + 'static {
        /// Report optional request fields this decoder can consume. Advertising
        /// multiple features means they may be used together in one decode request.
        async fn get_capabilities(
            &self,
            request: tonic::Request<()>,
        ) -> std::result::Result<
            tonic::Response<super::DecoderCapabilities>,
            tonic::Status,
        >;
        /// calling this service is in general inefficient because it has to process
        /// the entire decoding hypergraph during runtime. Consider using preloaded
        /// decoder instances like the rpc interfaces followed
        async fn decode(
            &self,
            request: tonic::Request<super::DecodingProblem>,
        ) -> std::result::Result<tonic::Response<super::ParityFactor>, tonic::Status>;
        /// load a decoding hypergraph into the decoder service so that the runtime
        /// decoding can simply decode using the existing instances
        async fn load_hypergraph(
            &self,
            request: tonic::Request<super::DecodingHypergraph>,
        ) -> std::result::Result<
            tonic::Response<super::LoadHypergraphResponse>,
            tonic::Status,
        >;
        /// decode using a preloaded hypergraph instance
        async fn decode_loaded(
            &self,
            request: tonic::Request<super::LoadedDecodingProblem>,
        ) -> std::result::Result<tonic::Response<super::ParityFactor>, tonic::Status>;
        /// remove all loaded hypergraph instances
        async fn reset(
            &self,
            request: tonic::Request<super::ResetRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct BlackBoxDecoderServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BlackBoxDecoderServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BlackBoxDecoderServer<T>
    where
        T: BlackBoxDecoder,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/deq.decoder.blackbox_decoder.BlackBoxDecoder/GetCapabilities" => {
                    #[allow(non_camel_case_types)]
                    struct GetCapabilitiesSvc<T: BlackBoxDecoder>(pub Arc<T>);
                    impl<T: BlackBoxDecoder> tonic::server::UnaryService<()>
                    for GetCapabilitiesSvc<T> {
                        type Response = super::DecoderCapabilities;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(&mut self, request: tonic::Request<()>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BlackBoxDecoder>::get_capabilities(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetCapabilitiesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.decoder.blackbox_decoder.BlackBoxDecoder/Decode" => {
                    #[allow(non_camel_case_types)]
                    struct DecodeSvc<T: BlackBoxDecoder>(pub Arc<T>);
                    impl<
                        T: BlackBoxDecoder,
                    > tonic::server::UnaryService<super::DecodingProblem>
                    for DecodeSvc<T> {
                        type Response = super::ParityFactor;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DecodingProblem>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BlackBoxDecoder>::decode(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DecodeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.decoder.blackbox_decoder.BlackBoxDecoder/LoadHypergraph" => {
                    #[allow(non_camel_case_types)]
                    struct LoadHypergraphSvc<T: BlackBoxDecoder>(pub Arc<T>);
                    impl<
                        T: BlackBoxDecoder,
                    > tonic::server::UnaryService<super::DecodingHypergraph>
                    for LoadHypergraphSvc<T> {
                        type Response = super::LoadHypergraphResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DecodingHypergraph>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BlackBoxDecoder>::load_hypergraph(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoadHypergraphSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.decoder.blackbox_decoder.BlackBoxDecoder/DecodeLoaded" => {
                    #[allow(non_camel_case_types)]
                    struct DecodeLoadedSvc<T: BlackBoxDecoder>(pub Arc<T>);
                    impl<
                        T: BlackBoxDecoder,
                    > tonic::server::UnaryService<super::LoadedDecodingProblem>
                    for DecodeLoadedSvc<T> {
                        type Response = super::ParityFactor;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoadedDecodingProblem>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BlackBoxDecoder>::decode_loaded(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DecodeLoadedSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.decoder.blackbox_decoder.BlackBoxDecoder/Reset" => {
                    #[allow(non_camel_case_types)]
                    struct ResetSvc<T: BlackBoxDecoder>(pub Arc<T>);
                    impl<
                        T: BlackBoxDecoder,
                    > tonic::server::UnaryService<super::ResetRequest> for ResetSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ResetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BlackBoxDecoder>::reset(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ResetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BlackBoxDecoderServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "deq.decoder.blackbox_decoder.BlackBoxDecoder";
    impl<T> tonic::server::NamedService for BlackBoxDecoderServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
