"""Regression tests for check plugins.

Each test case renders a Mako template with specific variables (selecting
a check plugin), transpiles the result, then compares the tag-stripped
protobuf output against a committed ``.ref.deq`` reference file that was
previously generated by ``deq annotate``.

To update reference files after an *intentional* plugin change, run the
``Makefile`` inside the corresponding fixture directory, review the diff,
and commit.
"""

from pathlib import Path

import pytest

from deq.circuit.mako_support import render_mako
from deq.circuit.parser import parse
from deq.cli.strip_tags import strip_jit_library
from deq.transpiler.jit_library_builder import build_jit_library

FIXTURES_DIR = Path(__file__).resolve().parent / "check_optimizer_fixtures"

# (fixture_dir, template, mako_vars, ref_stem)
_CASES = [
    # repetition_code
    (
        "repetition_code",
        "repetition_code.deq",
        {"d": "3", "finder": '"auto"'},
        "repetition_code_d3.auto",
    ),
    (
        "repetition_code",
        "repetition_code.deq",
        {"d": "3", "finder": '"syndrome"'},
        "repetition_code_d3.syndrome",
    ),
    (
        "repetition_code",
        "repetition_code.deq",
        {"d": "3", "finder": '"syndrome",metachecks=1'},
        "repetition_code_d3.syndrome-meta",
    ),
    (
        "repetition_code",
        "repetition_code.deq",
        {"d": "3", "finder": '"transversal"'},
        "repetition_code_d3.transversal",
    ),
    # surface_code
    (
        "surface_code",
        "surface_code.deq",
        {"d": "3", "finder": '"auto"'},
        "surface_code_d3.auto",
    ),
    (
        "surface_code",
        "surface_code.deq",
        {"d": "3", "finder": '"syndrome"'},
        "surface_code_d3.syndrome",
    ),
    (
        "surface_code",
        "surface_code.deq",
        {"d": "3", "finder": '"syndrome",metachecks=1'},
        "surface_code_d3.syndrome-meta",
    ),
    (
        "surface_code",
        "surface_code.deq",
        {"d": "3", "finder": '"transversal"'},
        "surface_code_d3.transversal",
    ),
    # code422
    (
        "code422",
        "code422.deq",
        {"finder": '"auto"'},
        "code422.auto",
    ),
    (
        "code422",
        "code422.deq",
        {"finder": '"syndrome"'},
        "code422.syndrome",
    ),
    (
        "code422",
        "code422.deq",
        {"finder": '"syndrome",metachecks=1'},
        "code422.syndrome-meta",
    ),
    (
        "code422",
        "code422.deq",
        {"finder": '"transversal"'},
        "code422.transversal",
    ),
]


def _transpile_and_strip(text: str) -> bytes:
    """Parse, transpile, strip tags, return serialized protobuf bytes."""
    qfile = parse(text)
    library = build_jit_library(qfile)
    stripped, _ = strip_jit_library(library)
    return stripped.SerializeToString()


@pytest.mark.parametrize(
    "fixture_dir, template, mako_vars, ref_stem",
    _CASES,
    ids=[c[3] for c in _CASES],
)
def test_check_plugin_matches_reference(
    fixture_dir: str,
    template: str,
    mako_vars: dict[str, str],
    ref_stem: str,
) -> None:
    dirpath = FIXTURES_DIR / fixture_dir
    template_path = dirpath / template
    ref_path = dirpath / f"{ref_stem}.ref.deq"

    template_text = template_path.read_text(encoding="utf-8")
    rendered = render_mako(template_text, mako_vars, template_dir=str(dirpath))
    original_bytes = _transpile_and_strip(rendered)

    ref_text = ref_path.read_text(encoding="utf-8")
    ref_bytes = _transpile_and_strip(ref_text)

    assert original_bytes == ref_bytes, (
        f"Transpiled output of {template} (with {mako_vars}) differs from "
        f"{ref_path.name}. If the change is intentional, regenerate the "
        f"reference file by running 'make' in {dirpath}."
    )
