"""Regression tests for the DEPOLARIZE1/2 -> independent-mechanism
conversion in ``enumerate_noise_mechanisms`` (#68).

Covers: exact conversion values, the composition property (the emitted
independent mechanisms XOR-compose back to the channel's per-Pauli
marginals), and the domain guards.
"""

import pytest

from deq.circuit.model import (
    GadgetDefinition,
    Instruction,
    LossTarget,
    PauliTarget,
    QubitTarget,
)
from deq.transpiler.jit_noise_builder import (
    _collect_noise_mechanisms,
    _real_measurement_count,
    enumerate_noise_mechanisms,
)
from deq.transpiler.loss.analysis import _collect_loss_sources


def _mechanisms(name, p, qubits):
    instr = Instruction(
        name, arguments=[p], targets=[QubitTarget(q) for q in qubits]
    )
    return enumerate_noise_mechanisms(instr, max(qubits) + 1)


def _xor_compose(mechanisms, num_qubits):
    """Distribution over the Pauli group (mod phase) generated by firing
    each mechanism independently; group elements are 2-bit-per-qubit
    (x, z) vectors composed by XOR."""

    def vec(pauli):
        v = 0
        for q in range(num_qubits):
            v |= {0: 0b00, 1: 0b01, 2: 0b11, 3: 0b10}[pauli[q]] << (2 * q)
        return v

    dist = {0: 1.0}
    for pauli, prob in mechanisms:
        nxt = {}
        for k, pr in dist.items():
            nxt[k] = nxt.get(k, 0.0) + pr * (1.0 - prob)
            nxt[k ^ vec(pauli)] = nxt.get(k ^ vec(pauli), 0.0) + pr * prob
        dist = nxt
    return dist


def test_depolarize1_exact_value():
    mechs = _mechanisms("DEPOLARIZE1", 0.15, [0])
    assert len(mechs) == 3
    q = (1.0 - (1.0 - 4.0 * 0.15 / 3.0) ** 0.5) / 2.0
    for _, prob in mechs:
        assert prob == pytest.approx(q)
        assert prob == pytest.approx(0.05278640450004207)


def test_depolarize2_exact_value():
    mechs = _mechanisms("DEPOLARIZE2", 0.3, [0, 1])
    assert len(mechs) == 15
    for _, prob in mechs:
        assert prob == pytest.approx(0.023532131586197547)


@pytest.mark.parametrize("p", [1e-4, 1e-3, 0.01, 0.15, 0.5, 0.74])
def test_depolarize1_composes_back_to_channel(p):
    dist = _xor_compose(_mechanisms("DEPOLARIZE1", p, [0]), 1)
    assert dist[0] == pytest.approx(1.0 - p)
    for v in (0b01, 0b10, 0b11):
        assert dist[v] == pytest.approx(p / 3.0)


@pytest.mark.parametrize("p", [1e-3, 0.05, 0.3, 0.9])
def test_depolarize2_composes_back_to_channel(p):
    dist = _xor_compose(_mechanisms("DEPOLARIZE2", p, [0, 1]), 2)
    assert dist[0] == pytest.approx(1.0 - p)
    for v in range(1, 16):
        assert dist[v] == pytest.approx(p / 15.0)


def test_depolarize1_rejects_overmixing():
    with pytest.raises(ValueError, match="3/4"):
        _mechanisms("DEPOLARIZE1", 0.76, [0])


def test_depolarize2_rejects_overmixing():
    with pytest.raises(ValueError, match="15/16"):
        _mechanisms("DEPOLARIZE2", 0.94, [0, 1])


def test_single_mechanism_channels_unchanged():
    ((_, prob),) = _mechanisms("X_ERROR", 0.05, [0])
    assert prob == pytest.approx(0.05)


def test_pair_measurement_produces_one_real_result_per_pair():
    instruction = Instruction(
        "MXX", targets=[QubitTarget(0), QubitTarget(1)]
    )

    assert _real_measurement_count(instruction) == 1


def test_noisy_pair_measurement_builds_one_flip_error_per_pair():
    from deq.circuit.parser import parse
    from deq.transpiler.jit_library_builder import build_jit_library

    library = build_jit_library(
        parse(
            """
            GADGET G {
                MXX(0.1) 0 1
                READOUT rec[-1]
            }
            """
        )
    )
    gadget = library.gadget_types[0]

    assert len(gadget.base.measurements) == 1
    assert len(gadget.errors) == 1
    assert list(gadget.errors[0].base.readout_flips) == [0]


def _correlated_instr(name, p, paulis):
    from deq.circuit.model import PauliTarget

    return Instruction(
        name,
        arguments=[p],
        targets=[PauliTarget(pauli, q) for pauli, q in paulis],
    )


def test_correlated_error_uses_literal_probability():
    instr = _correlated_instr("CORRELATED_ERROR", 0.2, [("X", 1), ("Y", 2)])
    ((_, prob),) = enumerate_noise_mechanisms(instr, 3)
    assert prob == pytest.approx(0.2)


@pytest.mark.parametrize("targets", ["X1", "L1", "L1 X0"])
@pytest.mark.parametrize(
    "prefix",
    [
        "",
        "CORRELATED_ERROR(0.2) X0\nTICK",
        "CORRELATED_ERROR(0.2) X0\nH 0",
        "CORRELATED_ERROR(0.2) X0\nLOSS_ERROR(0.1) 0",
        "CORRELATED_ERROR(0.2) X0\nREADOUT rec[-1]",
    ],
)
def test_compiler_rejects_else_without_an_active_chain(prefix, targets):
    from deq.circuit.parser import parse
    from deq.transpiler.jit_library_builder import build_jit_library

    source = f"""GADGET G {{
        R 0 1
        M 0
        {prefix}
        ELSE_CORRELATED_ERROR(0.5) {targets}
        M 0 1
        READOUT rec[-2] rec[-1]
    }}"""
    parsed = parse(source)
    gadget = parsed.definitions[0]
    assert isinstance(gadget, GadgetDefinition)

    with pytest.raises(
        ValueError, match="ELSE_CORRELATED_ERROR must immediately follow"
    ):
        build_jit_library(parsed)
    with pytest.raises(
        ValueError, match="ELSE_CORRELATED_ERROR must immediately follow"
    ):
        _collect_loss_sources(gadget.body)
    with pytest.raises(
        ValueError, match="ELSE_CORRELATED_ERROR must immediately follow"
    ):
        _collect_noise_mechanisms(
            gadget.body, 2, range(len(gadget.body)), len(gadget.body)
        )


@pytest.mark.parametrize("start_name", ["E", "CORRELATED_ERROR"])
@pytest.mark.parametrize("initial_probability", [0.0, 0.2, 1.0])
def test_collectors_preserve_correlated_chain_marginals(
    start_name, initial_probability
):
    body = [
        Instruction(
            start_name,
            arguments=[initial_probability],
            targets=[PauliTarget("X", 0)],
        ),
        Instruction(
            "ELSE_CORRELATED_ERROR", arguments=[0.25], targets=[LossTarget(1)]
        ),
        Instruction(
            "ELSE_CORRELATED_ERROR",
            arguments=[0.5],
            targets=[LossTarget(2), PauliTarget("X", 3)],
        ),
        Instruction("TICK"),
        Instruction(start_name, arguments=[0.4], targets=[LossTarget(4)]),
        Instruction(
            "ELSE_CORRELATED_ERROR", arguments=[0.5], targets=[PauliTarget("X", 5)]
        ),
        Instruction(start_name, arguments=[0.3], targets=[LossTarget(6)]),
        Instruction(
            "ELSE_CORRELATED_ERROR", arguments=[0.5], targets=[LossTarget(7)]
        ),
    ]
    pauli_priors = {
        mechanism.body_index: mechanism.probability
        for mechanism in _collect_noise_mechanisms(
            body, 8, range(len(body)), len(body)
        )
    }
    loss_priors = {
        source.body_index: source.probability for source in _collect_loss_sources(body)
    }

    assert set(pauli_priors) <= {0, 2, 5}
    assert [pauli_priors.get(index, 0.0) for index in (0, 2, 5)] == pytest.approx(
        [initial_probability, (1 - initial_probability) * 0.75 * 0.5, 0.3]
    )
    assert set(loss_priors) <= {1, 2, 4, 6, 7}
    assert [loss_priors.get(index, 0.0) for index in (1, 2, 4, 6, 7)] == pytest.approx(
        [
            (1 - initial_probability) * 0.25,
            (1 - initial_probability) * 0.75 * 0.5,
            0.4,
            0.3,
            0.35,
        ]
    )


@pytest.mark.parametrize(
    "name,remaining,expected_probability",
    [
        ("E", 0.8, 0.2),
        ("CORRELATED_ERROR", 0.8, 0.2),
        ("ELSE_CORRELATED_ERROR", 0.8, 0.16),
    ],
)
def test_mixed_correlated_loss_preserves_the_pauli_product(
    name, remaining, expected_probability
):
    instruction = Instruction(
        name,
        arguments=[0.2],
        targets=[LossTarget(0), PauliTarget("X", 1), PauliTarget("Y", 2)],
    )
    ((pauli, probability),) = enumerate_noise_mechanisms(
        instruction, 3, else_chain_remaining=remaining
    )
    assert str(pauli) == "+_XY"
    assert probability == pytest.approx(expected_probability)
    instruction.targets = [LossTarget(0), LossTarget(1)]
    assert enumerate_noise_mechanisms(instruction, 3) == []


def test_else_correlated_error_scales_by_chain_remaining():
    """Stim docs example: ``ELSE_CORRELATED_ERROR(0.25)`` after a
    ``CORRELATED_ERROR(0.2)`` has marginal probability ``0.25 * (1 - 0.2)``.
    """
    instr = _correlated_instr("ELSE_CORRELATED_ERROR", 0.25, [("Z", 2), ("Z", 3)])
    ((_, prob),) = enumerate_noise_mechanisms(
        instr, 4, else_chain_remaining=1.0 - 0.2
    )
    assert prob == pytest.approx(0.25 * (1.0 - 0.2))


def test_else_correlated_error_chain_three_terms():
    p1, p2, p3 = 0.2, 0.25, 0.33333333333
    instr1 = _correlated_instr("CORRELATED_ERROR", p1, [("X", 1), ("Y", 2)])
    instr2 = _correlated_instr("ELSE_CORRELATED_ERROR", p2, [("Z", 2), ("Z", 3)])
    instr3 = _correlated_instr(
        "ELSE_CORRELATED_ERROR", p3, [("X", 1), ("Y", 2), ("Z", 3)]
    )

    remaining = 1.0
    ((_, m1),) = enumerate_noise_mechanisms(instr1, 4, else_chain_remaining=remaining)
    remaining = (1.0 - p1) * remaining
    ((_, m2),) = enumerate_noise_mechanisms(instr2, 4, else_chain_remaining=remaining)
    remaining *= 1.0 - p2
    ((_, m3),) = enumerate_noise_mechanisms(instr3, 4, else_chain_remaining=remaining)

    assert m1 == pytest.approx(p1)
    assert m2 == pytest.approx(p2 * (1.0 - p1))
    assert m3 == pytest.approx(p3 * (1.0 - p1) * (1.0 - p2))
    # Total probability of *some* mechanism in the chain firing ≈ 0.6.
    assert m1 + m2 + m3 == pytest.approx(0.6, abs=1e-9)
