"""Regression tests for the DEPOLARIZE1/2 -> independent-mechanism
conversion in ``enumerate_noise_mechanisms`` (#68).

Covers: exact conversion values, the composition property (the emitted
independent mechanisms XOR-compose back to the channel's per-Pauli
marginals), and the domain guards.
"""

import pytest

from deq.circuit.model import Instruction, QubitTarget
from deq.transpiler.jit_noise_builder import enumerate_noise_mechanisms


def _mechanisms(name, p, qubits):
    instr = Instruction(
        name, arguments=[p], targets=[QubitTarget(q) for q in qubits]
    )
    return enumerate_noise_mechanisms(instr, max(qubits) + 1)


def _xor_compose(mechanisms, num_qubits):
    """Distribution over the Pauli group (mod phase) generated by firing
    each mechanism independently; group elements are 2-bit-per-qubit
    (x, z) vectors composed by XOR."""

    def vec(pauli):
        v = 0
        for q in range(num_qubits):
            v |= {0: 0b00, 1: 0b01, 2: 0b11, 3: 0b10}[pauli[q]] << (2 * q)
        return v

    dist = {0: 1.0}
    for pauli, prob in mechanisms:
        nxt = {}
        for k, pr in dist.items():
            nxt[k] = nxt.get(k, 0.0) + pr * (1.0 - prob)
            nxt[k ^ vec(pauli)] = nxt.get(k ^ vec(pauli), 0.0) + pr * prob
        dist = nxt
    return dist


def test_depolarize1_exact_value():
    mechs = _mechanisms("DEPOLARIZE1", 0.15, [0])
    assert len(mechs) == 3
    q = (1.0 - (1.0 - 4.0 * 0.15 / 3.0) ** 0.5) / 2.0
    for _, prob in mechs:
        assert prob == pytest.approx(q)
        assert prob == pytest.approx(0.05278640450004207)


def test_depolarize2_exact_value():
    mechs = _mechanisms("DEPOLARIZE2", 0.3, [0, 1])
    assert len(mechs) == 15
    for _, prob in mechs:
        assert prob == pytest.approx(0.023532131586197547)


@pytest.mark.parametrize("p", [1e-4, 1e-3, 0.01, 0.15, 0.5, 0.74])
def test_depolarize1_composes_back_to_channel(p):
    dist = _xor_compose(_mechanisms("DEPOLARIZE1", p, [0]), 1)
    assert dist[0] == pytest.approx(1.0 - p)
    for v in (0b01, 0b10, 0b11):
        assert dist[v] == pytest.approx(p / 3.0)


@pytest.mark.parametrize("p", [1e-3, 0.05, 0.3, 0.9])
def test_depolarize2_composes_back_to_channel(p):
    dist = _xor_compose(_mechanisms("DEPOLARIZE2", p, [0, 1]), 2)
    assert dist[0] == pytest.approx(1.0 - p)
    for v in range(1, 16):
        assert dist[v] == pytest.approx(p / 15.0)


def test_depolarize1_rejects_overmixing():
    with pytest.raises(ValueError, match="3/4"):
        _mechanisms("DEPOLARIZE1", 0.76, [0])


def test_depolarize2_rejects_overmixing():
    with pytest.raises(ValueError, match="15/16"):
        _mechanisms("DEPOLARIZE2", 0.94, [0, 1])


def test_single_mechanism_channels_unchanged():
    ((_, prob),) = _mechanisms("X_ERROR", 0.05, [0])
    assert prob == pytest.approx(0.05)


def _correlated_instr(name, p, paulis):
    from deq.circuit.model import PauliTarget

    return Instruction(
        name,
        arguments=[p],
        targets=[PauliTarget(pauli, q) for pauli, q in paulis],
    )


def test_correlated_error_uses_literal_probability():
    instr = _correlated_instr("CORRELATED_ERROR", 0.2, [("X", 1), ("Y", 2)])
    ((_, prob),) = enumerate_noise_mechanisms(instr, 3)
    assert prob == pytest.approx(0.2)


def test_else_correlated_error_scales_by_chain_remaining():
    """Stim docs example: ``ELSE_CORRELATED_ERROR(0.25)`` after a
    ``CORRELATED_ERROR(0.2)`` has marginal probability ``0.25 * (1 - 0.2)``.
    """
    instr = _correlated_instr("ELSE_CORRELATED_ERROR", 0.25, [("Z", 2), ("Z", 3)])
    ((_, prob),) = enumerate_noise_mechanisms(
        instr, 4, else_chain_remaining=1.0 - 0.2
    )
    assert prob == pytest.approx(0.25 * (1.0 - 0.2))


def test_else_correlated_error_chain_three_terms():
    p1, p2, p3 = 0.2, 0.25, 0.33333333333
    instr1 = _correlated_instr("CORRELATED_ERROR", p1, [("X", 1), ("Y", 2)])
    instr2 = _correlated_instr("ELSE_CORRELATED_ERROR", p2, [("Z", 2), ("Z", 3)])
    instr3 = _correlated_instr(
        "ELSE_CORRELATED_ERROR", p3, [("X", 1), ("Y", 2), ("Z", 3)]
    )

    remaining = 1.0
    ((_, m1),) = enumerate_noise_mechanisms(instr1, 4, else_chain_remaining=remaining)
    remaining = (1.0 - p1) * remaining
    ((_, m2),) = enumerate_noise_mechanisms(instr2, 4, else_chain_remaining=remaining)
    remaining *= 1.0 - p2
    ((_, m3),) = enumerate_noise_mechanisms(instr3, 4, else_chain_remaining=remaining)

    assert m1 == pytest.approx(p1)
    assert m2 == pytest.approx(p2 * (1.0 - p1))
    assert m3 == pytest.approx(p3 * (1.0 - p1) * (1.0 - p2))
    # Total probability of *some* mechanism in the chain firing ≈ 0.6.
    assert m1 + m2 + m3 == pytest.approx(0.6, abs=1e-9)
