"""Regression tests for the DEPOLARIZE1/2 -> independent-mechanism
conversion in ``enumerate_noise_mechanisms`` (#68).

Covers: exact conversion values, the composition property (the emitted
independent mechanisms XOR-compose back to the channel's per-Pauli
marginals), and the domain guards.
"""

import pytest

from deq.circuit.model import Instruction, QubitTarget
from deq.transpiler.jit_noise_builder import enumerate_noise_mechanisms


def _mechanisms(name, p, qubits):
    instr = Instruction(
        name, arguments=[p], targets=[QubitTarget(q) for q in qubits]
    )
    return enumerate_noise_mechanisms(instr, max(qubits) + 1)


def _xor_compose(mechanisms, num_qubits):
    """Distribution over the Pauli group (mod phase) generated by firing
    each mechanism independently; group elements are 2-bit-per-qubit
    (x, z) vectors composed by XOR."""

    def vec(pauli):
        v = 0
        for q in range(num_qubits):
            v |= {0: 0b00, 1: 0b01, 2: 0b11, 3: 0b10}[pauli[q]] << (2 * q)
        return v

    dist = {0: 1.0}
    for pauli, prob in mechanisms:
        nxt = {}
        for k, pr in dist.items():
            nxt[k] = nxt.get(k, 0.0) + pr * (1.0 - prob)
            nxt[k ^ vec(pauli)] = nxt.get(k ^ vec(pauli), 0.0) + pr * prob
        dist = nxt
    return dist


def test_depolarize1_exact_value():
    mechs = _mechanisms("DEPOLARIZE1", 0.15, [0])
    assert len(mechs) == 3
    q = (1.0 - (1.0 - 4.0 * 0.15 / 3.0) ** 0.5) / 2.0
    for _, prob in mechs:
        assert prob == pytest.approx(q)
        assert prob == pytest.approx(0.05278640450004207)


def test_depolarize2_exact_value():
    mechs = _mechanisms("DEPOLARIZE2", 0.3, [0, 1])
    assert len(mechs) == 15
    for _, prob in mechs:
        assert prob == pytest.approx(0.023532131586197547)


@pytest.mark.parametrize("p", [1e-4, 1e-3, 0.01, 0.15, 0.5, 0.74])
def test_depolarize1_composes_back_to_channel(p):
    dist = _xor_compose(_mechanisms("DEPOLARIZE1", p, [0]), 1)
    assert dist[0] == pytest.approx(1.0 - p)
    for v in (0b01, 0b10, 0b11):
        assert dist[v] == pytest.approx(p / 3.0)


@pytest.mark.parametrize("p", [1e-3, 0.05, 0.3, 0.9])
def test_depolarize2_composes_back_to_channel(p):
    dist = _xor_compose(_mechanisms("DEPOLARIZE2", p, [0, 1]), 2)
    assert dist[0] == pytest.approx(1.0 - p)
    for v in range(1, 16):
        assert dist[v] == pytest.approx(p / 15.0)


def test_depolarize1_rejects_overmixing():
    with pytest.raises(ValueError, match="3/4"):
        _mechanisms("DEPOLARIZE1", 0.76, [0])


def test_depolarize2_rejects_overmixing():
    with pytest.raises(ValueError, match="15/16"):
        _mechanisms("DEPOLARIZE2", 0.94, [0, 1])


def test_single_mechanism_channels_unchanged():
    ((_, prob),) = _mechanisms("X_ERROR", 0.05, [0])
    assert prob == pytest.approx(0.05)
