"""Generate outputs for the lattice-surgery tutorial chapter.

Runs ``deq annotate`` on ``01_mzz_before_conditional.deq`` so that the
``.annotated.deq`` file needed by the chapter's slice-link exists at
tutorial-build time.  The annotated file is gitignored and expected to
be regenerated by this script on each build (matches the pattern used
by other tutorial example folders such as ``compose-repropagate/``).

The chapter's "Why patch B is the correct port" subsection slice-links
the naive (pre-CONDITIONAL) PROPAGATE rows the annotator derives from
``01_mzz_before_conditional.deq``.  Committing the annotated file would
make the tutorial silently stale whenever the annotator's rendering
changes; regenerating on every ``make tutorial`` run keeps it honest.
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from snippet_utils import run_cli  # noqa: E402


this_dir = os.path.dirname(os.path.abspath(__file__))


run_cli(
    "annotate 01_mzz_before_conditional.deq",
    [
        "annotate",
        "--skip-mako-warning",
        os.path.join(this_dir, "01_mzz_before_conditional.deq"),
        "--out",
        os.path.join(this_dir, "01_mzz_before_conditional.annotated.deq"),
    ],
)
