parameters:
  - name: platforms
    type: object

stages:
  - stage: build_python_wheels
    displayName: Build Python Wheels (abi3)
    dependsOn: build
    condition: succeeded()
    jobs:
    - ${{ each platform in parameters.platforms }}:
      - job: Python_${{ platform.name }}_job
        pool:
          ${{ if platform.poolName }}:
            name: ${{ platform.poolName }}
          ${{ if platform.imageName }}:
            vmImage: ${{ platform.imageName }}
          os: ${{ platform.os }}
        timeoutInMinutes: 60
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: "Upload Python Artifacts"
            condition: succeeded()
            targetPath: $(System.DefaultWorkingDirectory)/target/wheels
            artifactName: ${{ platform.name }}-wheels
        steps:
        - task: UsePythonVersion@0
          displayName: Install Python 3.9
          inputs:
            versionSpec: "3.9"

        - task: RustInstaller@1
          inputs:
            rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
            cratesIoFeedOverride: $(cratesIoFeedOverride)
            toolchainFeed: $(toolchainFeed)
          displayName: Install Rust toolchain

        - bash: |
            python -m pip install --upgrade maturin
            mkdir -p target/wheels
            cd binar/bindings/python
            maturin build --release --out ../../../target/wheels
            cd ../../..
            cd paulimer/bindings/python
            maturin build --release --out ../../../target/wheels
          displayName: Build abi3 Python wheels
          env:
            RUSTFLAGS: "-C target-cpu=native"

        - bash: |
            ls -la target/wheels/
          displayName: List built wheels
