parameters:
  - name: platforms
    type: object

stages:
  - stage: build
    displayName: Build and Test All Crates
    jobs:
    - ${{ each platform in parameters.platforms }}:
        - job: ${{ platform.name }}
          displayName: Build ${{ platform.name }}
          ${{ if eq(platform.poolName, 'AcesShared') }}:
            pool:
              name: ${{ platform.poolName }}
              demands:
              - ImageOverride -equals ACES_VM_SharedPool_Sequoia
              os: ${{ platform.os }}
          ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
            pool:
              name: ${{ platform.poolName }}
              image: ${{ platform.imageName }}
              os: ${{ platform.os }}
              hostArchitecture: Arm64
          ${{ else }}:
            pool:
              name: ${{ platform.poolName }}
              image: ${{ platform.imageName }}
              os: ${{ platform.os }}
          variables:
            arch: ${{ platform.arch }}
          timeoutInMinutes: 60
          templateContext:
            outputs:
            - output: pipelineArtifact
              displayName: "Upload binar crate"
              condition: succeeded()
              targetPath: $(System.DefaultWorkingDirectory)/target/crates
              artifactName: binar-${{ platform.name }}-crate
            - output: pipelineArtifact
              displayName: "Upload paulimer crate"
              condition: succeeded()
              targetPath: $(System.DefaultWorkingDirectory)/target/crates_paulimer
              artifactName: paulimer-${{ platform.name }}-crate
            - output: pipelineArtifact
              displayName: "Upload pauliverse crate"
              condition: succeeded()
              targetPath: $(System.DefaultWorkingDirectory)/target/crates_pauliverse
              artifactName: pauliverse-${{ platform.name }}-crate
            - output: pipelineArtifact
              displayName: "Upload Python wheels"
              condition: succeeded()
              targetPath: $(System.DefaultWorkingDirectory)/target/wheels
              artifactName: ${{ platform.name }}-wheels
          steps:
          - script: |
              sudo tdnf install binutils glibc-devel kernel-headers patchelf gcc python3-3.12 python3-pip-3.12 python3-devel-3.12 -y
            displayName: Install build tools and Python on Linux aarch64
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq(variables['arch'], 'aarch64'))

          - ${{ if and(eq(platform.os, 'windows'), eq(platform.arch, 'aarch64')) }}:
              - pwsh: |
                  Write-Host "Downloading Python 3.11.9 for Windows ARM64..."
                  $url = "https://www.python.org/ftp/python/3.11.9/python-3.11.9-arm64.exe"
                  $output = "$env:TEMP\python-3.11.9-arm64.exe"
                  Invoke-WebRequest -Uri $url -OutFile $output
                  
                  Write-Host "Installing Python..."
                  Start-Process -FilePath $output -ArgumentList "/quiet", "InstallAllUsers=1", "PrependPath=1", "Include_test=0" -Wait -NoNewWindow
                  
                  Write-Host "Finding Python installation..."
                  $pythonPath = Get-ChildItem -Path "C:\Program Files\Python*" -Directory | 
                                Where-Object { $_.Name -match "Python3\d+" } | 
                                Select-Object -First 1 -ExpandProperty FullName
                  
                  if ($pythonPath) {
                      Write-Host "Found Python at: $pythonPath"
                      $env:Path = "$pythonPath;$pythonPath\Scripts;$env:Path"
                      Write-Host "##vso[task.setvariable variable=PATH]$pythonPath;$pythonPath\Scripts;$env:PATH"
                      & "$pythonPath\python.exe" --version
                  } else {
                      Write-Error "Python installation not found"
                      exit 1
                  }
                displayName: Install Python 3.11 on Windows ARM64

          - ${{ if not(and(eq(platform.os, 'windows'), eq(platform.arch, 'aarch64'))) }}:
              - ${{ if not(and(eq(platform.os, 'linux'), eq(platform.arch, 'aarch64'))) }}:
                  - task: UsePythonVersion@0
                    inputs:
                      versionSpec: "3.11"
                    displayName: Use Python 3.11

          - task: RustInstaller@1
            inputs:
              rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
              cratesIoFeedOverride: $(cratesIoFeedOverride)
              toolchainFeed: $(toolchainFeed)
            displayName: Install Rust toolchain

          - script: cargo build --release --all-features
            displayName: Build all crates
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - script: cargo test --release
            displayName: Test all crates
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - bash: |
              python3 -m venv .venv
              source .venv/bin/activate
              pip install --upgrade pip
              pip install maturin
              cd binar/bindings/python
              maturin develop --release
              cd ../../..
              python -c "import binar; print(binar.__version__)"
            displayName: Test binar Python bindings (Unix)
            condition: ne(variables['Agent.OS'], 'Windows_NT')

          - pwsh: |
              python -m venv .venv
              .\.venv\Scripts\Activate.ps1
              pip install --upgrade pip
              pip install maturin
              cd binar\bindings\python
              maturin develop --release
              cd ..\..\..
              python -c "import binar; print(binar.__version__)"
            displayName: Test binar Python bindings (Windows)
            condition: eq(variables['Agent.OS'], 'Windows_NT')

          - bash: |
              mkdir -p target/crates target/crates_paulimer target/crates_pauliverse target/wheels
              
              cd binar
              cargo package --allow-dirty --no-verify
              cd ..
              cp target/package/binar-*.crate target/crates/
              
              cd paulimer
              cargo package --allow-dirty --no-verify
              cd ..
              cp target/package/paulimer-*.crate target/crates_paulimer/
              
              cd pauliverse
              cargo package --allow-dirty --no-verify
              cd ..
              cp target/package/pauliverse-*.crate target/crates_pauliverse/
              
              source .venv/bin/activate
              cd binar/bindings/python
              maturin build --release --strip --out ../../../target/wheels
              cd ../../..
              
              ls -la target/crates/
              ls -la target/crates_paulimer/
              ls -la target/crates_pauliverse/
              ls -la target/wheels/
            displayName: Package crates and build wheels (Unix)
            condition: ne(variables['Agent.OS'], 'Windows_NT')

          - pwsh: |
              if (!(Test-Path target\crates)) { New-Item -ItemType Directory -Path target\crates }
              if (!(Test-Path target\crates_paulimer)) { New-Item -ItemType Directory -Path target\crates_paulimer }
              if (!(Test-Path target\crates_pauliverse)) { New-Item -ItemType Directory -Path target\crates_pauliverse }
              if (!(Test-Path target\wheels)) { New-Item -ItemType Directory -Path target\wheels }
              
              cd binar
              cargo package --allow-dirty --no-verify
              cd ..
              copy target\package\binar-*.crate target\crates\
              
              cd paulimer
              cargo package --allow-dirty --no-verify
              cd ..
              copy target\package\paulimer-*.crate target\crates_paulimer\
              
              cd pauliverse
              cargo package --allow-dirty --no-verify
              cd ..
              copy target\package\pauliverse-*.crate target\crates_pauliverse\
              
              .\.venv\Scripts\Activate.ps1
              cd binar\bindings\python
              maturin build --release --strip --out ..\..\..\target\wheels
              cd ..\..\..
              
              dir target\crates
              dir target\crates_paulimer
              dir target\crates_pauliverse
              dir target\wheels
            displayName: Package crates and build wheels (Windows)
            condition: eq(variables['Agent.OS'], 'Windows_NT')
