parameters:
  - name: platforms
    type: object
  - name: pythonVersions
    type: object

stages:
  - stage: build
    displayName: Build and Test
    jobs:
    - ${{ each platform in parameters.platforms }}:
      - ${{ each pythonVersion in parameters.pythonVersions }}:
        - job: ${{ platform.name }}_${{ replace(format('{0}', pythonVersion), '.', '') }}
          ${{ if eq(platform.poolName, 'AcesShared') }}:
            pool:
              name: ${{ platform.poolName }}
              demands:
              - ImageOverride -equals ACES_VM_SharedPool_Sequoia
              os: ${{ platform.os }}
          ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
            pool:
              name: ${{ platform.poolName }}
              ${{ if platform.imageName }}:
                image: ${{ platform.imageName }}
              os: ${{ platform.os }}
              hostArchitecture: Arm64
          ${{ else }}:
            pool:
              name: ${{ platform.poolName }}
              ${{ if platform.imageName }}:
                image: ${{ platform.imageName }}
              os: ${{ platform.os }}
          variables:
            pythonVersion: ${{ replace(format('{0}', pythonVersion), 'py', '') }}
          timeoutInMinutes: 90
          steps:
          - script: |
              sudo tdnf install binutils glibc-devel kernel-headers patchelf gcc -y
            displayName: Install build tools on Azure Linux 3.0 aarch64
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq('${{ platform.arch }}', 'aarch64'))

          - script: |
              sudo tdnf install -y python3-$(pythonVersion).*
              python$(pythonVersion) -m ensurepip --upgrade
              python$(pythonVersion) -m pip install --upgrade pip
            displayName: Install Python directly on Linux aarch64
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq('${{ platform.arch }}', 'aarch64'))

          - task: UsePythonVersion@0
            displayName: Install Python
            inputs:
              versionSpec: "$(pythonVersion)"
              ${{ if eq(platform.arch, 'aarch64') }}:
                architecture: "arm64"
            condition: not(and(eq(variables['Agent.OS'], 'Linux'), eq('${{ platform.arch }}', 'aarch64')))

          - task: RustInstaller@1
            inputs:
              rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
              cratesIoFeedOverride: $(cratesIoFeedOverride)
              toolchainFeed: $(toolchainFeed)
            displayName: Install Rust toolchain

          - script: msrustup --version && cargo --version && rustc --version
            displayName: Show toolchain details

          - script: cargo build --release --workspace --all-features
            displayName: Build workspace
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - bash: |
              python -m venv qdk_env
              source qdk_env/bin/activate
              python -m pip install --upgrade maturin pytest hypothesis more-itertools
              cd binar/bindings/python
              maturin develop --release
              cd ../../..
              cd paulimer/bindings/python
              maturin develop --release
            displayName: Build Python bindings (Linux/Mac)
            condition: ne( variables['Agent.OS'], 'Windows_NT')

          - script: |
              python -m venv qdk_env
              qdk_env\Scripts\python.exe -m pip install maturin pytest hypothesis more-itertools
              cd binar\bindings\python
              ..\..\..\qdk_env\Scripts\python.exe -m maturin develop --release
              cd ..\..\..
              cd paulimer\bindings\python
              ..\..\..\qdk_env\Scripts\python.exe -m maturin develop --release
            displayName: Build Python bindings (Windows)
            condition: eq( variables['Agent.OS'], 'Windows_NT')

          - bash: |
              source qdk_env/bin/activate
              cargo test --workspace --release
            displayName: Run tests (Linux/Mac)
            condition: ne( variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - script: |
              qdk_env\Scripts\python.exe -m pytest
              cargo test --workspace --release
            displayName: Run tests (Windows)
            condition: eq( variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"
