parameters:
  - name: platforms
    type: object
  - name: pythonVersions
    type: object

stages:
  - stage: build
    displayName: Build and Test
    jobs:
    - ${{ each platform in parameters.platforms }}:
      - ${{ each pythonVersion in parameters.pythonVersions }}:
        - job: ${{ platform.name }}_${{ replace(format('{0}', pythonVersion), '.', '') }}
          ${{ if eq(platform.poolName, 'AcesShared') }}:
            pool:
              name: ${{ platform.poolName }}
              demands:
              - ImageOverride -equals ACES_VM_SharedPool_Sequoia
              os: ${{ platform.os }}
          ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
            pool:
              name: ${{ platform.poolName }}
              ${{ if platform.imageName }}:
                image: ${{ platform.imageName }}
              os: ${{ platform.os }}
              hostArchitecture: Arm64
          ${{ else }}:
            pool:
              name: ${{ platform.poolName }}
              ${{ if platform.imageName }}:
                image: ${{ platform.imageName }}
              os: ${{ platform.os }}
          variables:
            pythonVersion: ${{ replace(format('{0}', pythonVersion), 'py', '') }}
          timeoutInMinutes: 90
          steps:
          - script: |
              sudo tdnf install binutils glibc-devel kernel-headers patchelf gcc -y
            displayName: Install build tools on Azure Linux 3.0 aarch64
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq('${{ platform.arch }}', 'aarch64'))

          - script: |
              sudo tdnf install -y python3-$(pythonVersion).*
              python$(pythonVersion) -m ensurepip --upgrade
              python$(pythonVersion) -m pip install --upgrade pip
            displayName: Install Python directly on Linux aarch64
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq('${{ platform.arch }}', 'aarch64'))

          - task: UsePythonVersion@0
            displayName: Install Python
            inputs:
              versionSpec: "$(pythonVersion)"
              githubToken: $(GitHubToken)
              ${{ if eq(platform.arch, 'aarch64') }}:
                architecture: "arm64"
            condition: not(and(eq(variables['Agent.OS'], 'Linux'), eq('${{ platform.arch }}', 'aarch64')))

          - script: |
              echo "=== Before venv ==="
              where python
              python --version
              python -m venv qdk_env && ^
              call qdk_env\Scripts\activate.bat && ^
              echo "=== After activation ===" && ^
              where python && ^
              python --version && ^
              echo "=== Pip configuration ===" && ^
              pip --version && ^
              pip config list -v && ^
              echo "=== Pip index URLs (if set) ===" && ^
              pip config get global.index-url 2>nul || echo "No global.index-url set" && ^
              pip config get install.index-url 2>nul || echo "No install.index-url set" && ^
              echo "=== Environment variables ===" && ^
              set | findstr /i "proxy" && ^
              set | findstr /i "pip" && ^
              echo "=== Installing packages ===" && ^
              pip install -vvv --upgrade maturin pytest hypothesis more-itertools && ^
              echo "=== Checking maturin ===" && ^
              where maturin && ^
              maturin --version && ^
              pip list && ^
              echo "=== Building binar ===" && ^
              cd binar\bindings\python && ^
              maturin develop --release && ^
              cd ..\..\.. && ^
              echo "=== Building paulimer ===" && ^
              cd paulimer\bindings\python && ^
              maturin develop --release
            displayName: Build Python bindings (Windows) - DEBUG
            condition: eq( variables['Agent.OS'], 'Windows_NT')

          - task: RustInstaller@1
            inputs:
              rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
              cratesIoFeedOverride: $(cratesIoFeedOverride)
              toolchainFeed: $(toolchainFeed)
            displayName: Install Rust toolchain

          - script: msrustup --version && cargo --version && rustc --version
            displayName: Show toolchain details

          - script: cargo build --release --all-features
            displayName: Build workspace
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - bash: |
              python -m venv qdk_env
              source qdk_env/bin/activate
              python -m pip install --upgrade maturin pytest hypothesis more-itertools
              cd binar/bindings/python
              maturin develop --release
              cd ../../..
              cd paulimer/bindings/python
              maturin develop --release
            displayName: Build Python bindings (Linux/Mac)
            condition: ne( variables['Agent.OS'], 'Windows_NT')

          # Duplicate Windows step removed - now runs immediately after Install Python

          - bash: |
              source qdk_env/bin/activate
              cargo test --release
            displayName: Run tests (Linux/Mac)
            condition: ne( variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - script: |
              qdk_env\Scripts\python.exe -m pytest
              cargo test --release
            displayName: Run tests (Windows)
            condition: eq( variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"
