parameters:
  - name: platforms
    type: object
  - name: pythonVersions
    type: object

stages:
  - stage: build
    displayName: Build and Test
    jobs:
    - ${{ each platform in parameters.platforms }}:
      - ${{ each pythonVersion in parameters.pythonVersions }}:
        - job: ${{ platform.name }}_${{ replace(format('{0}', pythonVersion), '.', '') }}
          pool:
            name: ${{ platform.poolName }}
            vmImage: ${{ platform.imageName }}
            os: ${{ platform.os }}
          variables:
            pythonVersion: ${{ replace(format('{0}', pythonVersion), 'py', '') }}
          timeoutInMinutes: 90
          steps:
          - task: UsePythonVersion@0
            displayName: Install Python
            inputs:
              versionSpec: "$(pythonVersion)"
              githubToken: $(GitHubToken)

          - task: PipAuthenticate@1
            displayName: Authenticate with Azure Artifacts
            inputs:
              artifactFeeds: 'qdk-ec'
              onlyAddExtraIndex: false

          - task: RustInstaller@1
            inputs:
              rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
              cratesIoFeedOverride: $(cratesIoFeedOverride)
              toolchainFeed: $(toolchainFeed)
            displayName: Install Rust toolchain

          - script: msrustup --version && cargo --version && rustc --version
            displayName: Show toolchain details

          - script: cargo build --release --all-features
            displayName: Build workspace
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - bash: |
              python -m venv qdk_env
              source qdk_env/bin/activate
              python -m pip install --upgrade maturin pytest hypothesis more-itertools
              cd binar/bindings/python
              maturin develop --release
              cd ../../..
              cd paulimer/bindings/python
              maturin develop --release
            displayName: Build Python bindings (Unix)
            condition: ne(variables['Agent.OS'], 'Windows_NT')

          - script: |
              python -m venv qdk_env
              call qdk_env\Scripts\activate.bat
              python -m pip install --upgrade maturin pytest hypothesis more-itertools
              cd binar\bindings\python
              maturin develop --release
              cd ..\..\..
              cd paulimer\bindings\python
              maturin develop --release
            displayName: Build Python bindings (Windows)
            condition: eq(variables['Agent.OS'], 'Windows_NT')

          - bash: |
              source qdk_env/bin/activate
              cargo test --release
            displayName: Run tests (Unix)
            condition: ne(variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - script: |
              call qdk_env\Scripts\activate.bat
              cargo test --release
            displayName: Run tests (Windows)
            condition: eq(variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"
