parameters:
  - name: platforms
    type: object

stages:
  - stage: build_python_wheels
    displayName: Build Python Wheels (abi3)
    dependsOn: build
    condition: succeeded()
    jobs:
    - ${{ each platform in parameters.platforms }}:
      - job: Python_${{ platform.name }}
        ${{ if eq(platform.poolName, 'AcesShared') }}:
          pool:
            name: ${{ platform.poolName }}
            demands:
            - ImageOverride -equals ACES_VM_SharedPool_Sequoia
            os: ${{ platform.os }}
        ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
          pool:
            name: ${{ platform.poolName }}
            image: ${{ platform.imageName }}
            os: ${{ platform.os }}
            hostArchitecture: Arm64
        ${{ else }}:
          pool:
            name: ${{ platform.poolName }}
            image: ${{ platform.imageName }}
            os: ${{ platform.os }}
        variables:
          arch: ${{ platform.arch }}
        timeoutInMinutes: 60
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: "Upload Python Artifacts"
            condition: succeeded()
            targetPath: $(System.DefaultWorkingDirectory)/target/wheels
            artifactName: ${{ platform.name }}-wheels
        steps:
        - script: |
            sudo tdnf install binutils glibc-devel kernel-headers patchelf gcc python3-3.12.* -y
            python3.12 -m ensurepip --upgrade
            python3.12 -m pip install --upgrade pip
          displayName: Install build tools and Python on Linux aarch64
          condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq(variables['arch'], 'aarch64'))

        - powershell: |
            Write-Host "Installing Python 3.11 via winget..."
            winget install Python.Python.3.11 --silent --disable-interactivity
            
            Write-Host "Adding Python to PATH..."
            $pythonPath = (Get-Command python).Source | Split-Path
            Write-Host "##vso[task.prependpath]$pythonPath"
            Write-Host "##vso[task.prependpath]$pythonPath\Scripts"
          displayName: Install Python via winget on Windows aarch64
          condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['arch'], 'aarch64'))

        - task: UsePythonVersion@0
          displayName: Install Python
          inputs:
            versionSpec: "3.11"
            githubToken: $(GitHubToken)
            ${{ if eq(platform.arch, 'aarch64') }}:
              architecture: "arm64"
            addToPath: true
          condition: and(not(and(eq(variables['Agent.OS'], 'Linux'), eq(variables['arch'], 'aarch64'))), not(and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['arch'], 'aarch64'))))

        - task: PipAuthenticate@1
          displayName: Authenticate with Azure Artifacts
          inputs:
            artifactFeeds: 'AzureQuantum/qdk-ec'
            onlyAddExtraIndex: true

        - bash: |
            echo "=== Pip config ==="
            pip config list -v
            echo "=== Pip config file ==="
            cat ~/.config/pip/pip.conf 2>/dev/null || echo "No pip.conf found"
            echo "=== Environment variables ==="
            env | grep -i pip || echo "No PIP_ variables"
          displayName: Debug pip configuration

        - task: RustInstaller@1
          inputs:
            rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
            cratesIoFeedOverride: $(cratesIoFeedOverride)
            toolchainFeed: $(toolchainFeed)
          displayName: Install Rust toolchain

        - bash: |
            python -m pip install --upgrade maturin
            mkdir -p target/wheels
            cd binar/bindings/python
            maturin build --release --out ../../../target/wheels
            cd ../../..
            cd paulimer/bindings/python
            maturin build --release --out ../../../target/wheels
          displayName: Build abi3 Python wheels
          env:
            RUSTFLAGS: "-C target-cpu=native"

        - bash: |
            ls -la target/wheels/
          displayName: List built wheels
