parameters:
  - name: platforms
    type: object
  - name: pythonVersions
    type: object

stages:
  - stage: build_python_wheels
    displayName: Build Python Wheels
    dependsOn: build
    condition: succeeded()
    jobs:
    - ${{ each platform in parameters.platforms }}:
      - ${{ each pythonVersion in parameters.pythonVersions }}:
        - job: Python_${{ platform.name }}_py${{ replace(pythonVersion, '.', '') }}_job
          ${{ if eq(platform.poolName, 'AcesShared') }}:
            pool:
              name: ${{ platform.poolName }}
              demands:
              - ImageOverride -equals ACES_VM_SharedPool_Sequoia
              os: ${{ platform.os }}
          ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
            pool:
              name: ${{ platform.poolName }}
              ${{ if platform.imageName }}:
                image: ${{ platform.imageName }}
              os: ${{ platform.os }}
              hostArchitecture: Arm64
          ${{ else }}:
            pool:
              name: ${{ platform.poolName }}
              ${{ if platform.imageName }}:
                image: ${{ platform.imageName }}
              os: ${{ platform.os }}
          variables:
            pythonVersion: '${{ pythonVersion }}'
          timeoutInMinutes: 60
          templateContext:
            outputs:
            - output: pipelineArtifact
              displayName: "Upload Python Artifacts Mac"
              condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
              targetPath: $(System.DefaultWorkingDirectory)/target/wheels
              artifactName: mac-${{ platform.arch }}-wheels-python${{ pythonVersion }}
            - output: pipelineArtifact
              displayName: "Upload Python Artifacts Win"
              condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
              targetPath: $(System.DefaultWorkingDirectory)/target/wheels
              artifactName: windows-${{ platform.arch }}-wheels-python${{ pythonVersion }}
            - output: pipelineArtifact
              displayName: "Upload Python Artifacts Linux"
              condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
              targetPath: $(System.DefaultWorkingDirectory)/target/wheels
              artifactName: linux-${{ platform.arch }}-wheels-python${{ pythonVersion }}
          steps:
          - task: UsePythonVersion@0
            displayName: Install Python
            inputs:
              versionSpec: "$(pythonVersion)"

          - task: RustInstaller@1
            inputs:
              rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
              cratesIoFeedOverride: $(cratesIoFeedOverride)
              toolchainFeed: $(toolchainFeed)
            displayName: Install Rust toolchain

          - bash: |
              python -m pip install --upgrade maturin
              mkdir -p target/wheels
              cd binar/bindings/python
              maturin build --release --out ../../../target/wheels
              cd ../../..
              cd paulimer/bindings/python
              maturin build --release --out ../../../target/wheels
            displayName: Build Python wheels (Linux/Mac)
            condition: ne( variables['Agent.OS'], 'Windows_NT')

          - script: |
              python -m pip install --upgrade maturin
              if not exist target\wheels mkdir target\wheels
              cd binar\bindings\python
              maturin build --release --out ..\..\..\target\wheels
              cd ..\..\..
              cd paulimer\bindings\python
              maturin build --release --out ..\..\..\target\wheels
            displayName: Build Python wheels (Windows)
            condition: eq( variables['Agent.OS'], 'Windows_NT')

          - bash: |
              ls -la target/wheels/
            displayName: List built wheels (Linux/Mac)
            condition: ne( variables['Agent.OS'], 'Windows_NT')

          - script: |
              dir target\wheels\
            displayName: List built wheels (Windows)
            condition: eq( variables['Agent.OS'], 'Windows_NT')
