parameters:
  - name: platforms
    type: object

stages:
  - stage: build_python_wheels
    displayName: Build Python Wheels (abi3)
    dependsOn: build
    condition: succeeded()
    jobs:
    - ${{ each platform in parameters.platforms }}:
      - job: Python_${{ platform.name }}_job
        ${{ if eq(platform.poolName, 'AcesShared') }}:
          pool:
            name: ${{ platform.poolName }}
            demands:
            - ImageOverride -equals ACES_VM_SharedPool_Sequoia
            os: ${{ platform.os }}
        ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
          pool:
            name: ${{ platform.poolName }}
            ${{ if platform.imageName }}:
              image: ${{ platform.imageName }}
            os: ${{ platform.os }}
            hostArchitecture: Arm64
        ${{ else }}:
          pool:
            name: ${{ platform.poolName }}
            ${{ if platform.imageName }}:
              image: ${{ platform.imageName }}
            os: ${{ platform.os }}
        timeoutInMinutes: 60
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: "Upload Python Artifacts Mac"
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
            targetPath: $(System.DefaultWorkingDirectory)/target/wheels
            artifactName: mac-${{ platform.arch }}-wheels
          - output: pipelineArtifact
            displayName: "Upload Python Artifacts Windows"
            condition: and(succeeded(), contains('${{ platform.target }}', 'windows'))
            targetPath: $(System.DefaultWorkingDirectory)/target/wheels
            artifactName: windows-${{ platform.arch }}-wheels
          - output: pipelineArtifact
            displayName: "Upload Python Artifacts Linux"
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), not(contains('${{ platform.target }}', 'windows')))
            targetPath: $(System.DefaultWorkingDirectory)/target/wheels
            artifactName: linux-${{ platform.arch }}-wheels
        steps:
        - script: |
            sudo tdnf install binutils glibc-devel kernel-headers patchelf gcc python3-3.9.* -y
            python3.9 -m ensurepip --upgrade
            python3.9 -m pip install --upgrade pip
          displayName: Install build tools and Python on Linux aarch64
          condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq('${{ platform.arch }}', 'aarch64'))

        - task: UsePythonVersion@0
          displayName: Install Python 3.9
          inputs:
            versionSpec: "3.9"
            ${{ if eq(platform.arch, 'aarch64') }}:
              architecture: "arm64"
          condition: not(and(eq(variables['Agent.OS'], 'Linux'), eq('${{ platform.arch }}', 'aarch64')))

        - task: RustInstaller@1
          inputs:
            rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
            cratesIoFeedOverride: $(cratesIoFeedOverride)
            toolchainFeed: $(toolchainFeed)
            ${{ if ne(platform.target, '') }}:
              additionalTargets: ${{ platform.target }}
          displayName: Install Rust toolchain

        - bash: |
            python -m pip install --upgrade maturin
            mkdir -p target/wheels
            
            # Build binar
            cd binar/bindings/python
            if [ -n "${{ platform.target }}" ]; then
              maturin build --release --target ${{ platform.target }} --out ../../../target/wheels
            else
              maturin build --release --out ../../../target/wheels
            fi
            cd ../../..
            
            # Build paulimer
            cd paulimer/bindings/python
            if [ -n "${{ platform.target }}" ]; then
              maturin build --release --target ${{ platform.target }} --out ../../../target/wheels
            else
              maturin build --release --out ../../../target/wheels
            fi
          displayName: Build abi3 Python wheels
          condition: ne( variables['Agent.OS'], 'Windows_NT')
          ${{ if eq(platform.target, '') }}:
            env:
              RUSTFLAGS: "-C target-cpu=native"

        - bash: |
            ls -la target/wheels/
          displayName: List built wheels
          condition: ne( variables['Agent.OS'], 'Windows_NT')
