parameters:
  - name: platforms
    type: object

stages:
  - stage: build_python_wheels
    displayName: Build Python Wheels (abi3)
    dependsOn: build
    condition: succeeded()
    jobs:
    - ${{ each platform in parameters.platforms }}:
      - job: Python_${{ platform.name }}
        ${{ if eq(platform.poolName, 'AcesShared') }}:
          pool:
            name: ${{ platform.poolName }}
            demands:
            - ImageOverride -equals ACES_VM_SharedPool_Sequoia
            os: ${{ platform.os }}
        ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
          pool:
            name: ${{ platform.poolName }}
            vmImage: ${{ platform.imageName }}
            os: ${{ platform.os }}
            hostArchitecture: Arm64
        ${{ else }}:
          pool:
            name: ${{ platform.poolName }}
            vmImage: ${{ platform.imageName }}
            os: ${{ platform.os }}
        timeoutInMinutes: 60
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: "Upload Python Artifacts"
            condition: succeeded()
            targetPath: $(System.DefaultWorkingDirectory)/target/wheels
            artifactName: ${{ platform.name }}-wheels
        steps:
        - script: |
            sudo tdnf install binutils glibc-devel kernel-headers patchelf gcc python3-3.11.* -y
            python3.11 -m ensurepip --upgrade
            python3.11 -m pip install --upgrade pip
          displayName: Install build tools and Python on Linux aarch64
          condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq('${{ platform.arch }}', 'aarch64'))

        - task: UsePythonVersion@0
          displayName: Install Python
          inputs:
            versionSpec: "3.11"
            githubToken: $(GitHubToken)
            ${{ if eq(platform.arch, 'aarch64') }}:
              architecture: "arm64"
          condition: not(and(eq(variables['Agent.OS'], 'Linux'), eq('${{ platform.arch }}', 'aarch64')))

        - task: PipAuthenticate@1
          displayName: Authenticate with Azure Artifacts
          inputs:
            artifactFeeds: 'qdk-ec'
            onlyAddExtraIndex: false

        - task: RustInstaller@1
          inputs:
            rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
            cratesIoFeedOverride: $(cratesIoFeedOverride)
            toolchainFeed: $(toolchainFeed)
          displayName: Install Rust toolchain

        - bash: |
            python -m pip install --upgrade maturin
            mkdir -p target/wheels
            cd binar/bindings/python
            maturin build --release --out ../../../target/wheels
            cd ../../..
            cd paulimer/bindings/python
            maturin build --release --out ../../../target/wheels
          displayName: Build abi3 Python wheels
          env:
            RUSTFLAGS: "-C target-cpu=native"

        - bash: |
            ls -la target/wheels/
          displayName: List built wheels
