parameters:
  - name: platforms
    type: object

stages:
  - stage: build
    displayName: Build and Test
    jobs:
    - ${{ each platform in parameters.platforms }}:
      - job: ${{ platform.name }}
        ${{ if eq(platform.poolName, 'AcesShared') }}:
          pool:
            name: ${{ platform.poolName }}
            demands:
            - ImageOverride -equals ACES_VM_SharedPool_Sequoia
            os: ${{ platform.os }}
        ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
          pool:
            name: ${{ platform.poolName }}
            ${{ if platform.imageName }}:
              image: ${{ platform.imageName }}
            os: ${{ platform.os }}
            hostArchitecture: Arm64
        ${{ else }}:
          pool:
            name: ${{ platform.poolName }}
            ${{ if platform.imageName }}:
              image: ${{ platform.imageName }}
            os: ${{ platform.os }}
        timeoutInMinutes: 90
        steps:
        - script: |
            sudo tdnf install binutils glibc-devel kernel-headers patchelf gcc -y
          displayName: Install build tools on Azure Linux 3.0 aarch64
          condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq('${{ platform.arch }}', 'aarch64'))

        - task: RustInstaller@1
          inputs:
            rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
            cratesIoFeedOverride: $(cratesIoFeedOverride)
            toolchainFeed: $(toolchainFeed)
          displayName: Install Rust toolchain

        - script: msrustup --version && cargo --version && rustc --version
          displayName: Show toolchain details

        - script: cargo build --release --workspace --all-features
          displayName: Build workspace
          env:
            RUSTFLAGS: "-C target-cpu=native"

        - script: cargo test --workspace --release
          displayName: Run tests
          env:
            RUSTFLAGS: "-C target-cpu=native"
