parameters:
  - name: platforms
    type: object

stages:
  - stage: build
    displayName: Build, Test, and Package
    jobs:
    - ${{ each platform in parameters.platforms }}:
        - job: ${{ platform.name }}
          ${{ if eq(platform.poolName, 'AcesShared') }}:
            pool:
              name: ${{ platform.poolName }}
              demands:
              - ImageOverride -equals ACES_VM_SharedPool_Sequoia
              os: ${{ platform.os }}
          ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
            pool:
              name: ${{ platform.poolName }}
              image: ${{ platform.imageName }}
              os: ${{ platform.os }}
              hostArchitecture: Arm64
          ${{ else }}:
            pool:
              name: ${{ platform.poolName }}
              image: ${{ platform.imageName }}
              os: ${{ platform.os }}
          variables:
            arch: ${{ platform.arch }}
          timeoutInMinutes: 90
          templateContext:
            outputs:
            - output: pipelineArtifact
              displayName: "Upload Python Wheels"
              condition: succeeded()
              targetPath: $(System.DefaultWorkingDirectory)/target/wheels
              artifactName: ${{ platform.name }}-wheels
            - output: pipelineArtifact
              displayName: "Upload Rust Crates"
              condition: succeeded()
              targetPath: $(System.DefaultWorkingDirectory)/target/crates
              artifactName: ${{ platform.name }}-crates
          steps:
          - script: |
              sudo tdnf install binutils glibc-devel kernel-headers patchelf gcc -y
            displayName: Install build tools on Linux aarch64
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq(variables['arch'], 'aarch64'))

          - script: |
              sudo tdnf install -y python3-3.12.*
              python3.12 -m ensurepip --upgrade
              python3.12 -m pip install --upgrade pip
            displayName: Install Python 3.12 on Linux aarch64
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq(variables['arch'], 'aarch64'))

          - powershell: |
              $version = "3.11.9"
              $installerUrl = "https://www.python.org/ftp/python/$version/python-$version-arm64.exe"
              $installerPath = "$env:TEMP\python-installer.exe"
              
              Write-Host "Downloading Python $version installer for ARM64..."
              Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath
              
              Write-Host "Installing Python silently..."
              Start-Process -FilePath $installerPath -ArgumentList '/quiet', 'InstallAllUsers=0', 'PrependPath=1', 'Include_pip=1' -Wait
              
              Write-Host "Finding Python installation..."
              Start-Sleep -Seconds 2
              $pythonPath = Get-ChildItem -Path "$env:LOCALAPPDATA\Programs\Python" -Filter "Python*" -Directory | Select-Object -First 1 -ExpandProperty FullName
              
              if ($pythonPath) {
                Write-Host "Found Python at: $pythonPath"
                Write-Host "##vso[task.prependpath]$pythonPath"
                Write-Host "##vso[task.prependpath]$pythonPath\Scripts"
                
                Write-Host "Verifying installation..."
                & "$pythonPath\python.exe" --version
              } else {
                Write-Host "##vso[task.logissue type=error]Python installation directory not found"
                exit 1
              }
            displayName: Install Python on Windows aarch64
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['arch'], 'aarch64'))

          - task: UsePythonVersion@0
            displayName: Install Python 3.11
            inputs:
              versionSpec: "3.11"
              githubToken: $(GitHubToken)
              ${{ if eq(platform.arch, 'aarch64') }}:
                architecture: "arm64"
              addToPath: true
            condition: and(not(and(eq(variables['Agent.OS'], 'Linux'), eq(variables['arch'], 'aarch64'))), not(and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['arch'], 'aarch64'))))

          - task: PipAuthenticate@1
            displayName: Authenticate with Azure Artifacts
            inputs:
              artifactFeeds: 'AzureQuantum/qdk-ec'
              onlyAddExtraIndex: true

          - task: RustInstaller@1
            inputs:
              rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
              cratesIoFeedOverride: $(cratesIoFeedOverride)
              toolchainFeed: $(toolchainFeed)
            displayName: Install Rust toolchain

          - script: msrustup --version && cargo --version && rustc --version
            displayName: Show toolchain details

          - script: cargo build --release --all-features
            displayName: Build workspace
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - bash: |
              # Use python3 on Unix systems (more reliable)
              if command -v python3 &> /dev/null; then
                PYTHON=python3
              elif command -v python &> /dev/null; then
                PYTHON=python
              elif [ "${{ platform.arch }}" = "aarch64" ] && [ "$(uname -s)" = "Linux" ]; then
                PYTHON=python3.12
              else
                echo "ERROR: No Python found"
                exit 1
              fi
              echo "Using Python: $PYTHON"
              $PYTHON --version
              $PYTHON -m venv qdk_env
              source qdk_env/bin/activate
              python -m pip install --upgrade maturin pytest hypothesis more-itertools
              cd binar/bindings/python
              maturin develop --release
              cd ../../..
              cd paulimer/bindings/python
              maturin develop --release
            displayName: Build Python bindings (Unix)
            condition: ne(variables['Agent.OS'], 'Windows_NT')

          - script: |
              python -m venv qdk_env
              call qdk_env\Scripts\activate.bat
              python -m pip install --upgrade maturin pytest hypothesis more-itertools
              cd binar\bindings\python
              maturin develop --release
              cd ..\..\..
              cd paulimer\bindings\python
              maturin develop --release
            displayName: Build Python bindings (Windows)
            condition: eq(variables['Agent.OS'], 'Windows_NT')

          - bash: |
              source qdk_env/bin/activate
              cargo test --release
            displayName: Run tests (Unix)
            condition: ne(variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - script: |
              call qdk_env\Scripts\activate.bat
              cargo test --release
            displayName: Run tests (Windows)
            condition: eq(variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - bash: |
              source qdk_env/bin/activate
              mkdir -p target/wheels
              cd binar/bindings/python
              maturin build --release --out ../../../target/wheels
              cd ../../..
              cd paulimer/bindings/python
              maturin build --release --out ../../../target/wheels
              cd ../../..
              ls -la target/wheels/
            displayName: Build abi3 Python wheels (Unix)
            condition: ne(variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - script: |
              call qdk_env\Scripts\activate.bat
              if not exist target\wheels mkdir target\wheels
              cd binar\bindings\python
              maturin build --release --out ..\..\..\target\wheels
              cd ..\..\..
              cd paulimer\bindings\python
              maturin build --release --out ..\..\..\target\wheels
              cd ..\..\..
              dir target\wheels
            displayName: Build abi3 Python wheels (Windows)
            condition: eq(variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - bash: |
              mkdir -p target/crates
              cd binar
              cargo package --allow-dirty --no-verify
              cd ..
              echo "=== Contents of workspace target/package ==="
              ls -la target/package/
              cp target/package/binar-*.crate target/crates/
              cd paulimer
              cargo package --allow-dirty --no-verify || echo "paulimer packaging failed (expected - dependencies)"
              cd ..
              if ls target/package/paulimer-*.crate 1> /dev/null 2>&1; then
                cp target/package/paulimer-*.crate target/crates/
              fi
              cd pauliverse
              cargo package --allow-dirty --no-verify || echo "pauliverse packaging failed (expected - dependencies)"
              cd ..
              if ls target/package/pauliverse-*.crate 1> /dev/null 2>&1; then
                cp target/package/pauliverse-*.crate target/crates/
              fi
              ls -la target/crates/
            displayName: Package Rust crates (Unix)
            condition: ne(variables['Agent.OS'], 'Windows_NT')

          - script: |
              if not exist target\crates mkdir target\crates
              cd binar
              cargo package --allow-dirty --no-verify
              copy target\package\binar-*.crate ..\target\crates\
              cd ..
              cd paulimer
              cargo package --allow-dirty --no-verify
              copy target\package\paulimer-*.crate ..\target\crates\
              cd ..
              cd pauliverse
              cargo package --allow-dirty --no-verify
              copy target\package\pauliverse-*.crate ..\target\crates\
              cd ..
              dir target\crates
            displayName: Package Rust crates (Windows)
            condition: eq(variables['Agent.OS'], 'Windows_NT')
