parameters:
- name: platforms
  type: object
- name: pythonVersions
  type: object

stages:
- stage: build
  displayName: Build and Test
  jobs:
  - ${{ each platform in parameters.platforms }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
      - job: ${{ platform.name }}_py${{ replace(pythonVersion, '.', '') }}
        pool:
          name: ${{ platform.poolName }}
          ${{ if platform.imageName }}:
            image: ${{ platform.imageName }}
          os: ${{ platform.os }}
          ${{ if platform.demands }}:
            demands: ${{ platform.demands }}
        variables:
          rustup_toolchain: $(RUST_TOOLCHAIN_VERSION)
          pythonVersion: ${{ pythonVersion }}
        timeoutInMinutes: 90
        steps:
        - task: RustInstaller@1
          inputs:
            rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
            cratesIoFeedOverride: $(cratesIoFeedOverride)
            toolchainFeed: $(toolchainFeed)
          displayName: Install Rust toolchain

        - script: rustup component add clippy rustfmt
          displayName: Install linting components (clippy, rustfmt, ...)

        - script: rustup --version && cargo --version && rustc --version && rustc --print target-cpus
          displayName: Show toolchain details

        - script: cargo build --workspace --all-features
          displayName: Build workspace
          env:
            RUSTFLAGS: "-C target-cpu=native"

        - script: cargo clippy-all
          displayName: Check code style and best practices (clippy)

        - script: cargo fmt --check
          displayName: Check code formatting (rustfmt)

        - script: cargo bench --no-run
          displayName: Build benchmarks
          env:
            RUSTFLAGS: "-C target-cpu=native"

        - task: UsePythonVersion@0
          displayName: Install Python
          inputs:
            versionSpec: "$(pythonVersion)"

        - bash: |
            python -m venv qdk_env
            source qdk_env/bin/activate
            python -m pip install --upgrade maturin pytest hypothesis more-itertools
            cd binar/bindings/python
            maturin develop --release
            cd ../../..
            cd paulimer/bindings/python
            maturin develop --release
          displayName: Build Python bindings (Linux/Mac)
          condition: ne( variables['Agent.OS'], 'Windows_NT')

        - script: |
            python -m venv qdk_env
            call qdk_env\Scripts\activate.bat
            python -m pip install --upgrade maturin pytest hypothesis more-itertools
            cd binar\bindings\python
            maturin develop --release
            cd ..\..\..
            cd paulimer\bindings\python
            maturin develop --release
          displayName: Build Python bindings (Windows)
          condition: eq( variables['Agent.OS'], 'Windows_NT')

        - bash: |
            source qdk_env/bin/activate
            cargo test --workspace --release
          displayName: Run tests (Linux/Mac)
          condition: ne( variables['Agent.OS'], 'Windows_NT')
          env:
            RUSTFLAGS: "-C target-cpu=native"

        - script: |
            call qdk_env\Scripts\activate.bat
            cargo test --workspace --release
          displayName: Run tests (Windows)
          condition: eq( variables['Agent.OS'], 'Windows_NT')
          env:
            RUSTFLAGS: "-C target-cpu=native"
