parameters:
  - name: platforms
    type: object
  - name: pythonVersions
    type: object

stages:
  - stage: build
    displayName: Build and Test
    jobs:
    - ${{ each platform in parameters.platforms }}:
      - ${{ each pythonVersion in parameters.pythonVersions }}:
        - job: ${{ platform.name }}_${{ replace(format('{0}', pythonVersion), '.', '') }}
          ${{ if eq(platform.poolName, 'AcesShared') }}:
            pool:
              name: ${{ platform.poolName }}
              demands:
              - ImageOverride -equals ACES_VM_SharedPool_Sequoia
              os: ${{ platform.os }}
          ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
            pool:
              name: ${{ platform.poolName }}
              image: ${{ platform.imageName }}
              os: ${{ platform.os }}
              hostArchitecture: Arm64
          ${{ else }}:
            pool:
              name: ${{ platform.poolName }}
              image: ${{ platform.imageName }}
              os: ${{ platform.os }}
          variables:
            pythonVersion: ${{ replace(format('{0}', pythonVersion), 'py', '') }}
            arch: ${{ platform.arch }}
          timeoutInMinutes: 90
          steps:
          - script: |
              sudo tdnf install binutils glibc-devel kernel-headers patchelf gcc -y
            displayName: Install build tools on Linux aarch64
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq(variables['arch'], 'aarch64'))

          # # Needed for Windows aarch Python install.
          # - task: UseNode@1
          #   inputs:
          #     version: "24.x"

          - script: |
              sudo tdnf install -y python3-3.12.*
              python3 -m ensurepip --upgrade
              python3 -m pip install --upgrade pip
            displayName: Install Python directly on Linux aarch64
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), eq(variables['arch'], 'aarch64'))

          - powershell: |
              $version = "$(pythonVersion)"
              $installerUrl = "https://www.python.org/ftp/python/$version/python-$version-arm64.exe"
              $installerPath = "$env:TEMP\python-installer.exe"
              
              Write-Host "Downloading Python $version installer for ARM64..."
              Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath
              
              Write-Host "Installing Python silently..."
              Start-Process -FilePath $installerPath -ArgumentList '/quiet', 'InstallAllUsers=0', 'PrependPath=1', 'Include_pip=1' -Wait
              
              Write-Host "Refreshing PATH..."
              $env:PATH = [System.Environment]::GetEnvironmentVariable('PATH', 'User') + ';' + [System.Environment]::GetEnvironmentVariable('PATH', 'Machine')
              
              Write-Host "Verifying installation..."
              python --version
            displayName: Install Python on Windows aarch64
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['arch'], 'aarch64'))

          - task: UsePythonVersion@0
            displayName: Install Python
            inputs:
              versionSpec: "$(pythonVersion)"
              githubToken: $(GitHubToken)
              ${{ if eq(platform.arch, 'aarch64') }}:
                architecture: "arm64"
              addToPath: true
            condition: and(not(and(eq(variables['Agent.OS'], 'Linux'), eq(variables['arch'], 'aarch64'))), not(and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['arch'], 'aarch64'))))

          - bash: |
              echo "Python in PATH:"
              which python || echo "python not found"
              which python3 || echo "python3 not found"
              python3 --version || python --version
            displayName: Debug Python installation
            condition: ne(variables['Agent.OS'], 'Windows_NT')

          - task: PipAuthenticate@1
            displayName: Authenticate with Azure Artifacts
            inputs:
              artifactFeeds: 'AzureQuantum/qdk-ec'
              onlyAddExtraIndex: true

          - bash: |
              echo "=== Pip config ==="
              pip config list -v
              echo "=== Pip config file (Unix) ==="
              cat ~/.config/pip/pip.conf 2>/dev/null || echo "No Unix pip.conf found"
              echo "=== Environment variables ==="
              env | grep -i pip || echo "No PIP_ variables"
            displayName: Debug pip configuration
            condition: ne(variables['Agent.OS'], 'Windows_NT')

          - script: |
              echo === Pip config ===
              pip config list -v
              echo === Pip config file (Windows) ===
              type %APPDATA%\pip\pip.ini 2>nul || echo No Windows pip.ini found
              echo === Environment variables ===
              set | findstr /i pip
            displayName: Debug pip configuration (Windows)
            condition: eq(variables['Agent.OS'], 'Windows_NT')

          - task: RustInstaller@1
            inputs:
              rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
              cratesIoFeedOverride: $(cratesIoFeedOverride)
              toolchainFeed: $(toolchainFeed)
            displayName: Install Rust toolchain

          - script: msrustup --version && cargo --version && rustc --version
            displayName: Show toolchain details

          - script: cargo build --release --all-features
            displayName: Build workspace
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - bash: |
              # Use python3 on Unix systems (more reliable)
              if command -v python3 &> /dev/null; then
                PYTHON=python3
              elif command -v python &> /dev/null; then
                PYTHON=python
              elif [ "${{ platform.arch }}" = "aarch64" ] && [ "$(uname -s)" = "Linux" ]; then
                PYTHON=python$(pythonVersion)
              else
                echo "ERROR: No Python found"
                exit 1
              fi
              echo "Using Python: $PYTHON"
              $PYTHON --version
              $PYTHON -m venv qdk_env
              source qdk_env/bin/activate
              python -m pip install --upgrade maturin pytest hypothesis more-itertools
              cd binar/bindings/python
              maturin develop --release
              cd ../../..
              cd paulimer/bindings/python
              maturin develop --release
            displayName: Build Python bindings (Unix)
            condition: ne(variables['Agent.OS'], 'Windows_NT')

          - script: |
              python -m venv qdk_env
              call qdk_env\Scripts\activate.bat
              python -m pip install --upgrade maturin pytest hypothesis more-itertools
              cd binar\bindings\python
              maturin develop --release
              cd ..\..\..
              cd paulimer\bindings\python
              maturin develop --release
            displayName: Build Python bindings (Windows)
            condition: eq(variables['Agent.OS'], 'Windows_NT')

          - bash: |
              source qdk_env/bin/activate
              cargo test --release
            displayName: Run tests (Unix)
            condition: ne(variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"

          - script: |
              call qdk_env\Scripts\activate.bat
              cargo test --release
            displayName: Run tests (Windows)
            condition: eq(variables['Agent.OS'], 'Windows_NT')
            env:
              RUSTFLAGS: "-C target-cpu=native"
