parameters:
  - name: platforms
    type: object
  - name: crateName
    type: string
  - name: publishCrate
    type: boolean

stages:
  - stage: publish_${{ parameters.crateName }}
    displayName: Publish ${{ parameters.crateName }}
    dependsOn: build
    jobs:
    - job: Approval
      displayName: Approve ${{ parameters.crateName }} release
      condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), eq(${{ parameters.publishCrate }}, true))
      pool: server
      timeoutInMinutes: 1440
      steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440
        inputs:
          notifyUsers: ""
          instructions: "Please verify ${{ parameters.crateName }} artifacts and approve the release"
          onTimeout: "reject"

    - job: Publish
      displayName: Publish to crates.io
      dependsOn: Approval
      pool:
        name: "Azure-Pipelines-DevTools-EO"
        image: "ubuntu-latest"
        os: linux
      templateContext:
        type: releaseJob
        isProduction: true
        inputs:
        - ${{ each platform in parameters.platforms }}:
          - input: pipelineArtifact
            artifactName: ${{ parameters.crateName }}-${{ platform.name }}-crate
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/${{ platform.name }}
      steps:
      - script: |
          mkdir -p $(System.DefaultWorkingDirectory)/target/crates
          find $(System.DefaultWorkingDirectory)/artifacts -name "${{ parameters.crateName }}-*.crate" -exec cp {} $(System.DefaultWorkingDirectory)/target/crates/ \;
          ls -la $(System.DefaultWorkingDirectory)/target/crates/
        displayName: Collect ${{ parameters.crateName }} .crate files

      - task: EsrpRelease@10
        displayName: Publish ${{ parameters.crateName }} to crates.io
        inputs:
          connectedservicename: "PME ESRP Azure Connection"
          usemanagedidentity: true
          keyvaultname: "quantum-esrp-kv"
          signcertname: ESRPCert
          clientid: "832c049d-cd07-4c1c-bfa5-c07250d190cb"
          intent: 'packagedistribution'
          contenttype: 'Rust'
          contentsource: 'Folder'
          domaintenantid: "975f013f-7f24-47e8-a7d3-abc4752bf346"
          folderlocation: "$(System.DefaultWorkingDirectory)/target/crates"
          waitforreleasecompletion: true
          owners: "adpaetzn@microsoft.com"
          approvers: "adpaetzn@microsoft.com"
          mainpublisher: ESRPRELPACMAN
