parameters:
  - name: platforms
    type: object
  - name: publishBinar
    type: boolean
  - name: publishPaulimer
    type: boolean
  - name: publishPauliverse
    type: boolean

stages:
  - stage: publish_crates
    displayName: Publish Rust Crates
    dependsOn: approval
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), or(eq(${{ parameters.publishBinar }}, true), eq(${{ parameters.publishPaulimer }}, true), eq(${{ parameters.publishPauliverse }}, true)))
    jobs:
    - job: "Publish_Crates"
      pool:
        name: "Azure-Pipelines-DevTools-EO"
        image: "ubuntu-latest"
        os: linux
      templateContext:
        type: releaseJob
        isProduction: true
        inputs:
        # Download crates from all platforms
        - ${{ each platform in parameters.platforms }}:
          - input: pipelineArtifact
            artifactName: ${{ platform.name }}-crates
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/${{ platform.name }}
      steps:
      - script: |
          mkdir -p $(System.DefaultWorkingDirectory)/target/crates
        displayName: Create crates directory

      - script: |
          find $(System.DefaultWorkingDirectory)/artifacts -name "*.crate" -exec cp {} $(System.DefaultWorkingDirectory)/target/crates/ \;
        displayName: Collect all .crate files

      - script: |
          ls -la $(System.DefaultWorkingDirectory)/target/crates/
        displayName: List packaged crates

      - task: EsrpRelease@10
        condition: succeeded()
        displayName: Publish Rust crates to crates.io
        inputs:
          connectedservicename: "PME ESRP Azure Connection"
          usemanagedidentity: true
          keyvaultname: "quantum-esrp-kv"
          signcertname: ESRPCert
          clientid: "832c049d-cd07-4c1c-bfa5-c07250d190cb"
          intent: 'packagedistribution'
          contenttype: 'Rust'
          contentsource: 'Folder'
          domaintenantid: "975f013f-7f24-47e8-a7d3-abc4752bf346"
          folderlocation: "$(System.DefaultWorkingDirectory)/target/crates"
          waitforreleasecompletion: true
          owners: "adpaetzn@microsoft.com"
          approvers: "adpaetzn@microsoft.com"
          mainpublisher: ESRPRELPACMAN
