parameters:
  - name: platforms
    type: object
  - name: publishBinarPython
    type: boolean
  - name: publishPaulimerPython
    type: boolean

stages:
  - stage: publish_python
    displayName: Publish Python Packages
    dependsOn: build
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), or(eq(${{ parameters.publishBinarPython }}, true), eq(${{ parameters.publishPaulimerPython }}, true)))
    jobs:
    - job: "Publish_Python_Packages"
      pool:
        name: "Azure-Pipelines-DevTools-EO"
        image: "ubuntu-latest"
        os: linux
      templateContext:
        type: releaseJob
        isProduction: true
        inputs:
        # Collect all platform wheels
        - ${{ each platform in parameters.platforms }}:
          - input: pipelineArtifact
            artifactName: ${{ platform.name }}-wheels
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/${{ platform.name }}
      steps:
      - script: |
          mkdir -p $(System.DefaultWorkingDirectory)/target/wheels
        displayName: Create wheels directory

      - script: |
          find $(System.DefaultWorkingDirectory)/artifacts -name "binar-*.whl" -exec cp {} $(System.DefaultWorkingDirectory)/target/wheels/ \;
        displayName: Collect binar wheels
        condition: eq(${{ parameters.publishBinarPython }}, true)

      - script: |
          find $(System.DefaultWorkingDirectory)/artifacts -name "paulimer-*.whl" -exec cp {} $(System.DefaultWorkingDirectory)/target/wheels/ \;
        displayName: Collect paulimer wheels
        condition: eq(${{ parameters.publishPaulimerPython }}, true)

      - script: |
          ls -la $(System.DefaultWorkingDirectory)/target/wheels
        displayName: List collected wheels

      - task: EsrpRelease@9
        condition: succeeded()
        displayName: Publish Py Packages
        inputs:
          connectedservicename: "PME ESRP Azure Connection"
          usemanagedidentity: true
          keyvaultname: "quantum-esrp-kv"
          signcertname: ESRPCert
          clientid: "832c049d-cd07-4c1c-bfa5-c07250d190cb"
          contenttype: PyPi
          domaintenantid: "975f013f-7f24-47e8-a7d3-abc4752bf346"
          folderlocation: "$(System.DefaultWorkingDirectory)/target/wheels"
          waitforreleasecompletion: true
          owners: "adpaetzn@microsoft.com"
          approvers: "adpaetzn@microsoft.com"
          mainpublisher: ESRPRELPACMAN
