/*
 * qodec.h - C ABI for qodec.
 *
 * GENERATED by cbindgen from the qodec-c crate. DO NOT EDIT BY HAND.
 * Regenerate with: bindings/c/regenerate.sh
 *
 * Source of truth: bindings/c/src/lib.rs.
 *
 * Load with qodec_load, read the returned Qodec and its fields, then release
 * it with qodec_unload. Treat the root and all reachable storage as read-only.
 *
 * Conventions:
 *   - Ordinary collections are { count, items }; iterate 0 .. count.
 *   - Parity equations, string lists and selection patterns use flat storage
 *     with count + 1 offsets when nonempty. Do not read offsets when empty.
 *   - Strings are borrowed, NUL-terminated const char *. An absent optional
 *     string is NULL; an absent collection is empty.
 *     A string containing NUL fails C projection with QODEC_STATUS_ERROR.
 *   - QodecAction and QodecArgumentValue are tagged unions: switch on tag
 *     and read only the matching member. QodecReference is a flat struct.
 *   - Operands are blocks; parameters are declared classical inputs; arguments
 *     are values supplied to those parameters. QodecInstructionCall separates
 *     operands from arguments; both contain QodecArgument entries.
 *   - QodecParameter.kind describes the declared parameter type, while
 *     QodecArgumentValue.tag selects the supplied value's representation.
 *   - int32_t status codes; QODEC_STATUS_OK (0) is success and negative values
 *     are errors. After a failing status, qodec_last_error() returns a message
 *     for the calling thread, valid until its next recorded error.
 *   - A panic caught in qodec_load returns QODEC_STATUS_PANIC; a panic caught
 *     in qodec_find_gadget returns NULL. Both record an error message.
 *   - Every nested pointer borrows from the root and becomes invalid on unload.
 */

#ifndef QODEC_H
#define QODEC_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI revision. Bump for any breaking change to a signature, symbol, struct
 * layout or calling convention below.
 */
#define QODEC_ABI_VERSION 1

/**
 * The call succeeded.
 */
#define QODEC_STATUS_OK 0

/**
 * The qodec could not be loaded; see `qodec_last_error()`.
 */
#define QODEC_STATUS_ERROR -1

/**
 * `qodec_load` received a null argument or a non-UTF-8 path.
 */
#define QODEC_STATUS_INVALID_ARG -2

/**
 * A Rust panic was caught during `qodec_load`; see `qodec_last_error()`.
 */
#define QODEC_STATUS_PANIC -3

/**
 * `QodecReference.tag`: `circuit.readouts[index]`, a measurement-record bit
 * at a zero-based position in measurement order.
 */
#define QODEC_REFERENCE_CIRCUIT_READOUT 0

/**
 * `QodecReference.tag`: `readouts[index]`, a zero-based gadget readout position.
 */
#define QODEC_REFERENCE_READOUT 1

/**
 * `QodecReference.tag`: `{in,out}[entry].{stabilizers,x,z}[index]`, an
 * encoding sign. Only this tag uses `boundary`, `property` and `entry`.
 */
#define QODEC_REFERENCE_ENCODING_PROPERTY 2

/**
 * A literal parity bit. `index` is 0 or 1; all other fields are zero.
 */
#define QODEC_REFERENCE_CONSTANT 3

/**
 * `QodecReference.boundary`: the gadget's `inputs` (`in:` on disk).
 */
#define QODEC_BOUNDARY_IN 0

/**
 * `QodecReference.boundary`: the gadget's `outputs` (`out:` on disk).
 */
#define QODEC_BOUNDARY_OUT 1

/**
 * `QodecReference.property` — a stabilizer-generator sign.
 */
#define QODEC_PROPERTY_STABILIZER 0

/**
 * `QodecReference.property` — a logical-X operator sign.
 */
#define QODEC_PROPERTY_LOGICAL_X 1

/**
 * `QodecReference.property` — a logical-Z operator sign.
 */
#define QODEC_PROPERTY_LOGICAL_Z 2

/**
 * `QodecParameter.kind`: a runtime classical bit parameter, eligible in conditions.
 */
#define QODEC_PARAMETER_BIT 0

/**
 * `QodecParameter.kind`: a parameter accepting a compile-time real literal.
 */
#define QODEC_PARAMETER_NUMBER 1

/**
 * `QodecParameter.kind`: a parameter accepting a compile-time integer literal.
 */
#define QODEC_PARAMETER_INTEGER 2

/**
 * `QodecParameter.kind`: a parameter accepting a compile-time boolean literal.
 */
#define QODEC_PARAMETER_BOOLEAN 3

/**
 * `QodecParameter.kind`: a parameter accepting a compile-time string literal.
 */
#define QODEC_PARAMETER_STRING 4

/**
 * `QodecParameter.kind`: a parameter accepting a compile-time Pauli literal.
 */
#define QODEC_PARAMETER_PAULI 5

/**
 * A block type declared by an instruction set.
 */
typedef struct {
  /**
   * The block type's name, as instruction operands reference it.
   */
  const char *name;
  /**
   * How many logical qubits a block of this type encodes.
   */
  size_t encodes;
} QodecBlock;

/**
 * A borrowed run of block declarations.
 */
typedef struct {
  /**
   * How many block declarations there are.
   */
  size_t count;
  /**
   * The declarations; null when `count` is zero.
   */
  const QodecBlock *items;
} QodecBlocks;

/**
 * One positional block operand in an instruction's `in:` / `out:` list.
 *
 * Operands are nameless: position fixes the contiguous range the entry
 * occupies in the flat index space the action addresses.
 */
typedef struct {
  /**
   * The block type this entry's qubits are encoded in.
   */
  const char *block;
  /**
   * Whether the entry is variadic (`[block]` on disk).
   */
  bool is_variadic;
} QodecBlockOperand;

/**
 * A borrowed run of block operands.
 */
typedef struct {
  /**
   * How many operands there are.
   */
  size_t count;
  /**
   * The operands; null when `count` is zero.
   */
  const QodecBlockOperand *items;
} QodecBlockOperands;

/**
 * A list of strings, in compressed-sparse-row form.
 *
 * For `string_index < count`, `bytes + offsets[string_index]` is a borrowed,
 * NUL-terminated UTF-8 string. Offsets include the terminators. A string
 * containing NUL fails C projection. When `count == 0`, do not read either buffer.
 *
 * ```c
 * const QodecStrings *stabilizers = &encoding->code.stabilizers;
 * for (size_t string_index = 0; string_index < stabilizers->count; ++string_index) {
 *     puts(stabilizers->bytes + stabilizers->offsets[string_index]);
 * }
 * ```
 */
typedef struct {
  /**
   * How many strings there are.
   */
  size_t count;
  /**
   * `count + 1` offsets into `bytes`; null when `count` is zero.
   */
  const size_t *offsets;
  /**
   * The strings, concatenated, each NUL-terminated; null when `count` is zero.
   */
  const char *bytes;
  /**
   * Total length of `bytes` including every terminator.
   */
  size_t total;
} QodecStrings;

/**
 * A declared classical input to an instruction.
 */
typedef struct {
  /**
   * The parameter's name, as call sites and conditions reference it.
   */
  const char *name;
  /**
   * Its declared parameter type; one of the `QODEC_PARAMETER_*` values.
   * `BIT` is the runtime, condition-eligible type; the rest accept compile-time
   * literals. This is not a `QodecArgumentValue` tag.
   */
  uint8_t kind;
} QodecParameter;

/**
 * A borrowed run of parameter declarations.
 */
typedef struct {
  /**
   * How many parameters there are.
   */
  size_t count;
  /**
   * The parameters; null when `count` is zero.
   */
  const QodecParameter *items;
} QodecParameters;

/**
 * One operation in an instruction's formal semantics.
 *
 * In C, switch on `tag` and read only its matching union member. For example,
 * `QodecAction_Observe` selects `observe.observables`.
 */
enum QodecAction_Tag
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * Force the state into the +1 eigenspace of every operator listed.
   */
  QodecAction_Stabilize,
  /**
   * A Clifford unitary, as the tableau mapping `from[i]` to `to[i]`.
   */
  QodecAction_Clifford,
  /**
   * Apply a Pauli unitary.
   */
  QodecAction_Pauli,
  /**
   * Measure each observable, one classical bit per entry, in order.
   */
  QodecAction_Observe,
  /**
   * Rotate about `axis` by a literal angle or a referenced parameter's value.
   */
  QodecAction_Rotate,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum QodecAction_Tag QodecAction_Tag;
#else
typedef uint8_t QodecAction_Tag;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

typedef struct {
  QodecStrings paulis;
} QodecAction_Stabilize_Body;

typedef struct {
  QodecStrings from;
  QodecStrings to;
} QodecAction_Clifford_Body;

typedef struct {
  const char *pauli;
} QodecAction_Pauli_Body;

typedef struct {
  QodecStrings observables;
} QodecAction_Observe_Body;

typedef struct {
  const char *axis;
  /**
   * Whether the angle is a literal rather than a parameter reference.
   */
  bool angle_is_literal;
  /**
   * The angle, when `angle_is_literal`.
   */
  double angle_literal;
  /**
   * Parameter name when `angle_is_literal` is false; null for a literal.
   * `angle_operand` is the ABI field name for this parameter reference.
   */
  const char *angle_operand;
} QodecAction_Rotate_Body;

typedef struct {
  QodecAction_Tag tag;
  union {
    QodecAction_Stabilize_Body stabilize;
    QodecAction_Clifford_Body clifford;
    QodecAction_Pauli_Body pauli;
    QodecAction_Observe_Body observe;
    QodecAction_Rotate_Body rotate;
  };
} QodecAction;

/**
 * One step of an instruction's action, with its optional guard.
 */
typedef struct {
  /**
   * The operation this step performs.
   */
  QodecAction action;
  /**
   * Whether the step is guarded.
   */
  bool has_condition;
  /**
   * The bits XOR-ed to form the guard, when `has_condition`.
   */
  QodecStrings condition_predicates;
  /**
   * Whether the guard is inverted (`unless` rather than `if`), when `has_condition`.
   */
  bool condition_invert;
} QodecActionStep;

/**
 * A borrowed run of action steps.
 */
typedef struct {
  /**
   * How many steps there are.
   */
  size_t count;
  /**
   * The steps; null when `count` is zero.
   */
  const QodecActionStep *items;
} QodecActionSteps;

/**
 * One instruction declared by an instruction set.
 *
 * `QodecAction_Observe` steps declare measurement outcomes in action order.
 * `flags` declares additional named output bits.
 */
typedef struct {
  /**
   * The instruction's mnemonic.
   */
  const char *mnemonic;
  /**
   * Free-text description, or the empty string.
   */
  const char *description;
  /**
   * Input block operands (logical qubits consumed or passed through).
   */
  QodecBlockOperands inputs;
  /**
   * Output block operands (logical qubits produced or passed through).
   */
  QodecBlockOperands outputs;
  /**
   * Named classical outputs following the action's measurement outcomes.
   */
  QodecStrings flags;
  /**
   * Declared classical inputs; calls supply arguments for these parameters.
   */
  QodecParameters parameters;
  /**
   * The formal semantics: an ordered list of guarded operations.
   */
  QodecActionSteps action;
  /**
   * Free-form annotations as JSON object text, including `{}` when empty.
   */
  const char *metadata_json;
} QodecInstruction;

/**
 * A borrowed run of instructions, in declaration order.
 */
typedef struct {
  /**
   * How many instructions there are.
   */
  size_t count;
  /**
   * The instructions; null when `count` is zero.
   */
  const QodecInstruction *items;
} QodecInstructions;

/**
 * A borrowed run of numeric circuit-qubit identifiers, not array positions.
 *
 * Identifiers are `uint64_t` wherever they appear, including
 * `QodecArgumentValue.qubit.index`; counts are `size_t`.
 */
typedef struct {
  /**
   * How many indices there are.
   */
  size_t count;
  /**
   * The indices; null when `count` is zero.
   */
  const uint64_t *items;
} QodecIndices;

/**
 * A block label or an argument value supplied at a call site.
 *
 * Used by both `QodecInstructionCall.operands` and
 * `QodecInstructionCall.arguments`. The tag describes the supplied
 * representation, not the declared `QodecParameter.kind`.
 *
 * In C, switch on `tag` and read only its matching union member. For example,
 * `QodecArgumentValue_Qubit` selects `qubit.index`, not `integer.value`.
 */
enum QodecArgumentValue_Tag
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A numeric block label or qubit identifier, not a position in a projected array.
   */
  QodecArgumentValue_Qubit,
  /**
   * A list of numeric circuit-qubit identifiers.
   */
  QodecArgumentValue_QubitList,
  /**
   * An integer literal.
   */
  QodecArgumentValue_Integer,
  /**
   * A real literal.
   */
  QodecArgumentValue_Number,
  /**
   * A block label carried as text, or a string-valued argument.
   */
  QodecArgumentValue_Text,
  /**
   * A list of string literals.
   */
  QodecArgumentValue_StringList,
  /**
   * A prior measurement-record bit at an absolute, zero-based position in
   * measurement order across preceding calls.
   */
  QodecArgumentValue_Readout,
  /**
   * A Boolean literal, distinct from integer literals 0 and 1.
   */
  QodecArgumentValue_Boolean,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum QodecArgumentValue_Tag QodecArgumentValue_Tag;
#else
typedef uint8_t QodecArgumentValue_Tag;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

typedef struct {
  uint64_t index;
} QodecArgumentValue_Qubit_Body;

typedef struct {
  QodecIndices qubits;
} QodecArgumentValue_QubitList_Body;

typedef struct {
  int64_t value;
} QodecArgumentValue_Integer_Body;

typedef struct {
  double value;
} QodecArgumentValue_Number_Body;

typedef struct {
  const char *value;
} QodecArgumentValue_Text_Body;

typedef struct {
  QodecStrings strings;
} QodecArgumentValue_StringList_Body;

typedef struct {
  uint64_t index;
} QodecArgumentValue_Readout_Body;

typedef struct {
  bool value;
} QodecArgumentValue_Boolean_Body;

typedef struct {
  QodecArgumentValue_Tag tag;
  union {
    QodecArgumentValue_Qubit_Body qubit;
    QodecArgumentValue_QubitList_Body qubit_list;
    QodecArgumentValue_Integer_Body integer;
    QodecArgumentValue_Number_Body number;
    QodecArgumentValue_Text_Body text;
    QodecArgumentValue_StringList_Body string_list;
    QodecArgumentValue_Readout_Body readout;
    QodecArgumentValue_Boolean_Body boolean;
  };
} QodecArgumentValue;

/**
 * One block operand or parameter argument at a call site.
 */
typedef struct {
  /**
   * The parameter name for a named argument; null for a positional block operand.
   */
  const char *name;
  /**
   * The block label or supplied argument value.
   */
  QodecArgumentValue value;
} QodecArgument;

/**
 * A borrowed run of block operands or parameter arguments.
 */
typedef struct {
  /**
   * How many entries there are.
   */
  size_t count;
  /**
   * The entries; null when `count` is zero.
   */
  const QodecArgument *items;
} QodecArguments;

/**
 * One constraint in a `select` pattern: a flag bit and its expected value.
 */
typedef struct {
  /**
   * The call's flag, named or addressed by its zero-based `flags[<index>]` position.
   */
  const char *flag;
  /**
   * The value it is expected to take, `0` or `1`.
   */
  uint8_t bit;
} QodecSelectConstraint;

/**
 * Selection patterns over a call's own flags, in compressed-sparse-row form.
 *
 * Pattern `pattern_index` uses the borrowed range
 * `constraints[offsets[pattern_index] .. offsets[pattern_index + 1]]`.
 * A pattern matches when every constraint matches; selection matches when any
 * pattern matches. `count == 0` imposes no constraint.
 * Do not read offsets when `count == 0` or constraints when `total == 0`.
 */
typedef struct {
  /**
   * How many patterns there are.
   */
  size_t count;
  /**
   * `count + 1` offsets delimiting `constraints`; null when `count` is zero.
   */
  const size_t *offsets;
  /**
   * The patterns' constraints, concatenated.
   */
  const QodecSelectConstraint *constraints;
  /**
   * Total number of constraints. Zero when `count == 0`; otherwise `offsets[count]`.
   */
  size_t total;
} QodecSelect;

/**
 * One invocation of a `QodecInstruction` in a circuit.
 */
typedef struct {
  /**
   * The mnemonic invoked, naming an instruction in the circuit's instruction set.
   */
  const char *mnemonic;
  /**
   * Blocks in the instruction's declared operand order. Each `name` is null;
   * its value is a numeric label (`Qubit`) or a named label (`Text`).
   */
  QodecArguments operands;
  /**
   * Arguments supplied to the instruction's declared parameters, each carrying
   * the parameter name in `name`.
   */
  QodecArguments arguments;
  /**
   * Selection patterns over this call's flags; empty when no selection is specified.
   */
  QodecSelect select;
} QodecInstructionCall;

/**
 * A borrowed run of instruction calls, in program order.
 */
typedef struct {
  /**
   * How many calls there are.
   */
  size_t count;
  /**
   * The calls; null when `count` is zero.
   */
  const QodecInstructionCall *items;
} QodecInstructionCalls;

/**
 * A gadget's circuit: the program that runs, and the instruction set it calls into.
 */
typedef struct {
  /**
   * The name of the target instruction set the source calls into.
   */
  const char *instruction_set_name;
  /**
   * Inlined program text, preserved verbatim. NUL bytes fail C projection.
   */
  const char *source;
  /**
   * The resolved source-format tag, or null when inferred from the text.
   */
  const char *format;
  /**
   * The format selected for parsing: `format` when non-null, otherwise
   * inferred from the text. This does not guarantee a parser is available.
   */
  const char *effective_format;
  /**
   * Calls parsed and checked against the target instruction set during `qodec_load`.
   * Empty on a parse error, an undeclared instruction, or a program with no
   * calls. Check `error` to distinguish failure from an empty program.
   */
  QodecInstructionCalls calls;
  /**
   * Parse or instruction-check error, or null on success. This error leaves
   * `calls` empty without failing `qodec_load` and is not recorded in
   * `qodec_last_error`.
   */
  const char *error;
} QodecCircuit;

/**
 * One term of a parity equation, in fully expanded form.
 *
 * `tag` selects the reference kind. `boundary`, `property` and `entry` are
 * meaningful only for `QODEC_REFERENCE_ENCODING_PROPERTY` and are zero
 * otherwise. Every index is relative to the containing gadget.
 *
 * Selectors are already expanded: an authored `circuit.readouts[0,2,5]` is
 * three references.
 */
typedef struct {
  /**
   * Which reference shape this is; one of the `QODEC_REFERENCE_*` values.
   */
  uint8_t tag;
  /**
   * For an encoding property, one of the `QODEC_BOUNDARY_*` values.
   */
  uint8_t boundary;
  /**
   * For an encoding property, one of the `QODEC_PROPERTY_*` values.
   */
  uint8_t property;
  /**
   * For an encoding property, the zero-based encoding position in the
   * gadget's `inputs` or `outputs`, selected by `boundary`.
   */
  uint64_t entry;
  /**
   * Zero-based circuit or gadget readout position; for an encoding property,
   * the operator position in the encoding code's `stabilizers`, `x` or `z`.
   * For `QODEC_REFERENCE_CONSTANT`, the literal bit 0 or 1.
   */
  uint64_t index;
} QodecReference;

/**
 * A list of parity equations, in compressed-sparse-row form.
 *
 * Equation `equation_index` uses the borrowed range
 * `references[offsets[equation_index] .. offsets[equation_index + 1]]`.
 * This storage is shared by checks, readouts, and frames; only checks assert zero parity.
 * Do not read offsets when `count == 0` or references when `total == 0`.
 */
typedef struct {
  /**
   * How many equations there are.
   */
  size_t count;
  /**
   * `count + 1` offsets delimiting `references`; null when `count` is zero.
   */
  const size_t *offsets;
  /**
   * The equations' references, concatenated.
   */
  const QodecReference *references;
  /**
   * Total number of references. Zero when `count == 0`; otherwise `offsets[count]`.
   */
  size_t total;
} QodecParity;

/**
 * A quantum error-correcting code.
 */
typedef struct {
  /**
   * The code's name.
   */
  const char *name;
  /**
   * Free-text description, or the empty string.
   */
  const char *description;
  /**
   * Stabilizer generators, as Pauli strings.
   */
  QodecStrings stabilizers;
  /**
   * Logical X operators, one per logical qubit.
   */
  QodecStrings x;
  /**
   * Logical Z operators, one per logical qubit, aligned with `x`.
   */
  QodecStrings z;
  /**
   * Number of logical qubits, equal to `x.count`. A valid code declares as
   * many logical Z operators, but a draft need not: bound `z` by `z.count`.
   */
  size_t logical_count;
  /**
   * One more than the highest qubit index across stabilizers and logical
   * operators, or zero when none is used.
   */
  uint64_t physical_qubit_count;
  /**
   * Free-form annotations as JSON object text, including `{}` when empty.
   */
  const char *metadata_json;
} QodecCode;

/**
 * One boundary encoding: the code a gadget operand is encoded in, and where
 * that code's blocks land in the circuit.
 */
typedef struct {
  /**
   * The code this encoding uses.
   */
  QodecCode code;
  /**
   * Circuit-operand labels in code-block order, such as `"0"` or `"ancilla"`.
   * These are labels, not positions in a projected array.
   */
  QodecStrings support;
  /**
   * Block-type names parallel to `support`, or an empty list if unavailable.
   */
  QodecStrings block_types;
} QodecEncoding;

/**
 * A borrowed run of encodings.
 */
typedef struct {
  /**
   * How many encodings there are.
   */
  size_t count;
  /**
   * The encodings; null when `count` is zero.
   */
  const QodecEncoding *items;
} QodecEncodings;

/**
 * One gadget: the per-instruction rule lowering it to the layer below.
 */
typedef struct {
  /**
   * The instruction this gadget declares it implements.
   */
  QodecInstruction implements;
  /**
   * The circuit supplied for this implementation.
   */
  QodecCircuit circuit;
  /**
   * Declared zero-parity checks. Loading does not verify them against the circuit.
   */
  QodecParity checks;
  /**
   * Readout equations in output order: the instruction's `observe` outcomes
   * first, then its flags. These are not all zero-parity checks.
   */
  QodecParity readouts;
  /**
   * One name per readout, parallel to `readouts`; an empty string for an
   * anonymous readout. Names are labels, not reference indices.
   */
  QodecStrings readout_names;
  /**
   * Number of `observe` outcomes declared by the implemented instruction.
   * For `readout_index < readouts.count`, `readout_index >= observe_count`
   * identifies a flag. An incomplete draft may declare fewer readouts than
   * outcomes, so this can exceed `readouts.count`.
   */
  size_t observe_count;
  /**
   * Instruction parameter names forwarded into the circuit source, parallel
   * to `parameter_targets`.
   */
  QodecStrings parameter_names;
  /**
   * Circuit-source parameter names, parallel to `parameter_names`, without
   * the on-disk `circuit.source.` prefix.
   */
  QodecStrings parameter_targets;
  /**
   * Input boundary encodings. An encoding-property reference selects an
   * entry here when its `boundary` is `QODEC_BOUNDARY_IN`.
   */
  QodecEncodings inputs;
  /**
   * Output boundary encodings, indexed likewise for `QODEC_BOUNDARY_OUT`.
   */
  QodecEncodings outputs;
  /**
   * Free-form annotations as JSON object text, including `{}` when empty.
   */
  const char *metadata_json;
  /**
   * Output logical-sign reference paths in sorted order, parallel to `frames`.
   */
  QodecStrings frame_targets;
  /**
   * Additional output-sign corrections as XOR equations. Empty entries apply
   * no correction. These are definitions, not zero-parity checks.
   */
  QodecParity frames;
} QodecGadget;

/**
 * A borrowed run of gadgets, in sorted mnemonic order.
 * Ordering uses UTF-8 bytes.
 */
typedef struct {
  /**
   * How many gadgets there are.
   */
  size_t count;
  /**
   * The gadgets; null when `count` is zero.
   */
  const QodecGadget *items;
} QodecGadgets;

/**
 * One layer of the lowering chain: an instruction set plus the gadgets lowering it.
 */
typedef struct {
  /**
   * The name of this layer's instruction set.
   */
  const char *instruction_set_name;
  /**
   * The instruction set's description, or the empty string.
   */
  const char *instruction_set_description;
  /**
   * The block types the instruction set declares.
   */
  QodecBlocks blocks;
  /**
   * The instruction set's instructions, in declaration order.
   */
  QodecInstructions instructions;
  /**
   * The gadgets lowering this layer to the next. Empty on the bottom layer,
   * which is the target of the layer above and lowers no further.
   */
  QodecGadgets gadgets;
  /**
   * The instruction set's free-form annotations as JSON object text, including `{}` when empty.
   */
  const char *instruction_set_metadata_json;
} QodecLayer;

/**
 * A borrowed run of layers, ordered logical to physical.
 */
typedef struct {
  /**
   * How many layers there are.
   */
  size_t count;
  /**
   * The layers; null when `count` is zero.
   */
  const QodecLayer *items;
} QodecLayers;

/**
 * The root of a loaded qodec.
 *
 * Produced by `qodec_load()` and released by `qodec_unload()`. Treat this struct
 * and all reachable storage as read-only. All nested pointers borrow from
 * this root and become invalid when it is unloaded.
 *
 * Pass the original root pointer to `qodec_unload` exactly once, not a copy of
 * the struct. Never free the root or its nested storage yourself.
 */
typedef struct {
  /**
   * The qodec's name, or the empty string when the manifest has none.
   */
  const char *name;
  /**
   * The manifest description, or the empty string.
   */
  const char *description;
  /**
   * Whether the manifest declared an on-disk schema version.
   */
  bool has_schema_version;
  /**
   * The declared on-disk schema version; meaningful only when `has_schema_version`.
   */
  uint32_t schema_version;
  /**
   * The lowering chain, ordered logical to physical.
   */
  QodecLayers layers;
  /**
   * The manifest's free-form annotations as JSON object text, including `{}` when empty.
   */
  const char *metadata_json;
} Qodec;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The ABI revision this library implements.
 *
 * Compare it with `QODEC_ABI_VERSION` from the header before reading projected
 * structs. Do not use the projection if the revisions differ.
 */
uint32_t qodec_abi_version(void);

/**
 * The calling thread's most recent error, or null if there is none.
 *
 * The returned NUL-terminated string is read-only and borrows thread-local
 * storage. It remains valid until another error is recorded on this thread
 * or the thread exits. Copy it to retain the message; do not free it.
 *
 * Successful calls do not clear an older error. Check the load status or
 * lookup result before consulting this message.
 * NUL bytes in diagnostic text are escaped as `\0`.
 */
const char *qodec_last_error(void);

/**
 * Load a qodec from a manifest file or single-file bundle at `path`.
 * The path must name a file, not a directory, and must be UTF-8.
 *
 * Returns `QODEC_STATUS_OK` and writes the root to `*out_qodec` on success.
 * The root and all reachable storage are read-only; release the root with
 * `qodec_unload()`.
 *
 * On failure, leaves `*out_qodec` unchanged and records `qodec_last_error()`.
 * Returns `QODEC_STATUS_INVALID_ARG` for a null argument or non-UTF-8 path,
 * `QODEC_STATUS_ERROR` for a loader error (including a directory path) or a
 * string containing NUL in the C projection, or
 * `QODEC_STATUS_PANIC` for a caught Rust panic. Initialize the output pointer
 * to null before calling.
 *
 * Caller requirements:
 *
 * `path` must point to a valid, readable NUL-terminated C string. `out_qodec`
 * must be non-null, aligned and writable for one root pointer. Both must
 * remain valid for the duration of the call.
 */
int32_t qodec_load(const char *path, Qodec **out_qodec);

/**
 * Release a qodec from `qodec_load()`, invalidating everything reachable from
 * it. Null is a no-op.
 *
 * Caller requirements:
 *
 * A non-null `qodec` must be exactly the pointer `qodec_load()` produced, not
 * previously unloaded and not a copy of the struct. The root and its reachable
 * storage must not have been modified or freed. All readers must have finished;
 * unloading must not race with any read. Unloading twice is undefined behavior.
 */
void qodec_unload(Qodec *qodec);

/**
 * Find the first gadget in `layer` whose `implements.mnemonic` matches
 * `mnemonic`. The comparison is exact and case-sensitive.
 *
 * Returns a borrowed pointer, valid until the owning qodec is unloaded. Do not
 * modify or free it. Returns null and records `qodec_last_error()` for no match,
 * a null argument, or a caught Rust panic.
 *
 * Caller requirements:
 *
 * `layer` must be null or point to a valid, unmodified layer in a live qodec.
 * `mnemonic` must point to a valid, readable NUL-terminated C string for the
 * duration of the call. Keep the owning qodec alive during the call and while
 * using the returned pointer; unloading must not race with either use.
 */
const QodecGadget *qodec_find_gadget(const QodecLayer *layer, const char *mnemonic);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* QODEC_H */
