from typing import Iterable, final, Iterator, Literal, overload

Bits = str | Iterable[bool | Literal[0, 1]]

@final
class BitMatrix:
    def __init__(self, rows: Iterable["BitVector" | Bits]) -> None: ...
    @staticmethod
    def identity(dimension: int) -> "BitMatrix": ...
    @staticmethod
    def zeros(rows: int, columns: int) -> "BitMatrix": ...
    @staticmethod
    def ones(rows: int, columns: int) -> "BitMatrix": ...
    @staticmethod
    def _from_bytes(rows: int, columns: int, data: bytes) -> "BitMatrix": ...
    @property
    def rowcount(self) -> int: ...
    @property
    def columncount(self) -> int: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def rows(self) -> Iterator["BitVector"]: ...
    @property
    def T(self) -> "BitMatrix": ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    def copy(self) -> "BitMatrix": ...
    def reshape(self, rows: int, columns: int) -> None: ...
    def dot(self, other: "BitMatrix") -> "BitMatrix": ...
    def submatrix(self, rows: list[int], columns: list[int]) -> "BitMatrix": ...
    def echelonize(self) -> list[int]: ...
    def echelonized(self) -> "BitMatrix": ...
    def kernel(self) -> "BitMatrix": ...
    def __getitem__(self, index: tuple[int, int]) -> bool: ...
    def __setitem__(self, index: tuple[int, int], to: bool) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __add__(self, other: "BitMatrix") -> "BitMatrix": ...
    def __iadd__(self, other: "BitMatrix") -> None: ...
    def __mul__(self, other: "BitMatrix") -> "BitMatrix": ...
    @overload
    def __matmul__(self, other: "BitMatrix") -> "BitMatrix": ...
    @overload
    def __matmul__(self, other: "BitVector") -> "BitVector": ...
    def __xor__(self, other: "BitMatrix") -> "BitMatrix": ...
    def __ixor__(self, other: "BitMatrix") -> None: ...
    def __and__(self, other: "BitMatrix") -> "BitMatrix": ...
    def __iand__(self, other: "BitMatrix") -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def _to_bytes(self) -> bytes: ...

@final
class BitVector:
    def __init__(self, bits: Bits) -> None: ...
    @staticmethod
    def zeros(length: int) -> "BitVector": ...
    @staticmethod
    def ones(length: int) -> "BitVector": ...
    @staticmethod
    def _from_bytes(length: int, data: bytes) -> "BitVector": ...
    @property
    def weight(self) -> int: ...
    @property
    def parity(self) -> bool: ...
    @property
    def is_zero(self) -> bool: ...
    @property
    def support(self) -> list[int]: ...
    def resize(self, new_length: int) -> None: ...
    def clear(self) -> None: ...
    def negate_index(self, index: int) -> None: ...
    def dot(self, other: "BitVector") -> bool: ...
    def and_weight(self, other: "BitVector") -> int: ...
    def or_weight(self, other: "BitVector") -> int: ...
    def __iter__(self) -> Iterator[bool]: ...
    @overload
    def __getitem__(self, index: int) -> bool: ...
    @overload
    def __getitem__(self, index: slice) -> "BitVector": ...
    def __setitem__(self, index: int, to: bool) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __xor__(self, other: "BitVector") -> "BitVector": ...
    def __ixor__(self, other: "BitVector") -> None: ...
    def __and__(self, other: "BitVector") -> "BitVector": ...
    def __iand__(self, other: "BitVector") -> None: ...
    def __or__(self, other: "BitVector") -> "BitVector": ...
    def __ior__(self, other: "BitVector") -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def _to_bytes(self) -> bytes: ...


def vstack(matrices: Iterable[BitMatrix]) -> BitMatrix: ...

def rank(matrix: BitMatrix) -> int: ...
def null_space(matrix: BitMatrix) -> BitMatrix: ...
def inv(matrix: BitMatrix) -> BitMatrix: ...
def det(matrix: BitMatrix) -> bool: ...
def solve(matrix: BitMatrix, b: BitVector) -> BitVector | None: ...
