"""Generate outputs for the @REPROPAGATE tutorial chapter.

Runs the CLI commands referenced in ``compose-repropagate.md`` so that
breaking changes are caught by ``make tutorial``:

* transpile both .deq files;
* annotate the *passing* file (with @REPROPAGATE) and write the
  .annotated.deq output;
* annotate the *failing* file (without @REPROPAGATE), capture the
  user-visible error message, and write it to a .txt fixture that the
  chapter shows verbatim;
* extract the inlined Teleport GADGET block from the annotated output
  as a snippet for inline display.
"""

import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from snippet_utils import extract_block  # noqa: E402

this_dir = os.path.dirname(os.path.abspath(__file__))


def run_cli(description: str, args: list[str], *, allow_failure: bool = False):
    """Run a ``python -m deq ...`` command and return (returncode, stdout, stderr)."""
    print(f"  {description}...")
    result = subprocess.run(
        [sys.executable, "-m", "deq"] + args,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0 and not allow_failure:
        sys.stderr.write(result.stderr)
        raise RuntimeError(f"command failed: {' '.join(args)}")
    return result.returncode, result.stdout, result.stderr


def write(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"    -> {os.path.basename(path)}")


# ── Transpile both files (succeeds in both cases) ────────────────────

for name in ("01_teleport_logical.deq", "02_teleport_repropagate.deq"):
    path = os.path.join(this_dir, name)
    out = os.path.join(this_dir, f"{name}.jit")
    run_cli(
        f"transpile {name}",
        ["transpile", path, "--out", out, "--program", "Simulation"],
        allow_failure=True,  # stim export may complain on COMPOSE
    )


# ── Annotate the passing file (@REPROPAGATE) ─────────────────────────

annotated_02 = os.path.join(this_dir, "02_teleport_repropagate.annotated.deq")
run_cli(
    "annotate 02_teleport_repropagate.deq",
    [
        "annotate",
        os.path.join(this_dir, "02_teleport_repropagate.deq"),
        "--out",
        annotated_02,
    ],
)


# ── Annotate the failing file (no @REPROPAGATE) ──────────────────────
#
# `deq annotate` is expected to fail here at the round-trip verification
# step.  We capture the trailing user-visible error message (everything
# from the final ``ValueError:`` line to the end of stderr) and pin it
# in a text fixture so the chapter's quoted output stays in sync.

error_fixture = os.path.join(this_dir, "01_teleport_annotate_error.txt")
returncode, _stdout, stderr = run_cli(
    "annotate 01_teleport_logical.deq (expected to fail)",
    [
        "annotate",
        os.path.join(this_dir, "01_teleport_logical.deq"),
        "--out",
        os.path.join(this_dir, "01_teleport_logical.annotated.deq"),
    ],
    allow_failure=True,
)
if returncode == 0:
    raise RuntimeError(
        "expected `deq annotate` on 01_teleport_logical.deq to fail "
        "(no @REPROPAGATE), but it succeeded; the chapter's narrative "
        "no longer matches actual behaviour"
    )

match = re.search(r"^ValueError: .*\Z", stderr, flags=re.MULTILINE | re.DOTALL)
if match is None:
    sys.stderr.write(stderr)
    raise RuntimeError(
        "could not find the final ValueError in `deq annotate` stderr"
    )
error_text = match.group(0).rstrip() + "\n"
write(error_fixture, error_text)


# ── Extract snippets ─────────────────────────────────────────────────
#
# All ``snippet_*.deq`` files in ``examples/`` are gitignored — they are
# expected to be regenerated by the chapter's generator on each build.
# We extract them from the source .deq files using the shared
# ``extract_block`` helper so they always stay in sync.

with open(
    os.path.join(this_dir, "01_teleport_logical.deq"), encoding="utf-8"
) as f:
    src_01 = f.read()
write(
    os.path.join(this_dir, "snippet_teleport_compose.deq"),
    extract_block(src_01, "COMPOSE", "Teleport"),
)

with open(
    os.path.join(this_dir, "02_teleport_repropagate.deq"), encoding="utf-8"
) as f:
    src_02 = f.read()
write(
    os.path.join(this_dir, "snippet_teleport_compose_repropagate.deq"),
    extract_block(src_02, "COMPOSE", "Teleport"),
)

with open(annotated_02, encoding="utf-8") as f:
    annotated_text = f.read()
write(
    os.path.join(this_dir, "snippet_teleport_annotated.deq"),
    extract_block(annotated_text, "GADGET", "Teleport"),
)
