"""Generate outputs for the @REPROPAGATE tutorial chapter.

Runs the CLI commands referenced in ``compose-repropagate.md`` so that
breaking changes are caught by ``make tutorial``:

* transpile both .deq files;
* annotate both files and write the .annotated.deq outputs;
* extract the inlined Teleport GADGET block from the annotated output
  as a snippet for inline display.
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from snippet_utils import extract_block, run_cli, write_snippet  # noqa: E402

this_dir = os.path.dirname(os.path.abspath(__file__))


# ── Transpile both files (succeeds in both cases) ────────────────────

for name in ("01_teleport_logical.deq", "02_teleport_repropagate.deq"):
    path = os.path.join(this_dir, name)
    out = os.path.join(this_dir, f"{name}.jit")
    run_cli(
        f"transpile {name}",
        ["transpile", path, "--out", out, "--program", "Simulation"],
        allow_failure=True,  # stim export may complain on COMPOSE
    )


# ── Annotate both files ──────────────────────────────────────────────
#
# Under the current architecture the annotator emits ``PROPAGATE`` rows
# verbatim from the binary matrices for every COMPOSE-derived GADGET, so
# annotation succeeds for both the plain-COMPOSE (01) and the
# @REPROPAGATE-COMPOSE (02) file.  The semantic difference lies in how the
# propagation rows are *derived* (matrix composition vs. flat-circuit
# Heisenberg) and in the shape of the emitted ``PROPAGATE`` rows.

annotated_01 = os.path.join(this_dir, "01_teleport_logical.annotated.deq")
run_cli(
    "annotate 01_teleport_logical.deq",
    [
        "annotate",
        os.path.join(this_dir, "01_teleport_logical.deq"),
        "--out",
        annotated_01,
    ],
)

annotated_02 = os.path.join(this_dir, "02_teleport_repropagate.annotated.deq")
run_cli(
    "annotate 02_teleport_repropagate.deq",
    [
        "annotate",
        os.path.join(this_dir, "02_teleport_repropagate.deq"),
        "--out",
        annotated_02,
    ],
)


# ── Extract snippets ─────────────────────────────────────────────────
#
# All ``snippet_*.deq`` files in ``examples/`` are gitignored — they are
# expected to be regenerated by the chapter's generator on each build.
# We extract them from the source .deq files using the shared
# ``extract_block`` helper so they always stay in sync.

with open(
    os.path.join(this_dir, "01_teleport_logical.deq"), encoding="utf-8"
) as f:
    src_01 = f.read()
write_snippet(
    os.path.join(this_dir, "snippet_teleport_compose.deq"),
    extract_block(src_01, "COMPOSE", "Teleport"),
)

with open(
    os.path.join(this_dir, "02_teleport_repropagate.deq"), encoding="utf-8"
) as f:
    src_02 = f.read()
write_snippet(
    os.path.join(this_dir, "snippet_teleport_compose_repropagate.deq"),
    extract_block(src_02, "COMPOSE", "Teleport"),
)

with open(annotated_01, encoding="utf-8") as f:
    annotated_01_text = f.read()
write_snippet(
    os.path.join(this_dir, "snippet_teleport_plain_annotated.deq"),
    extract_block(annotated_01_text, "GADGET", "Teleport"),
)

with open(annotated_02, encoding="utf-8") as f:
    annotated_text = f.read()
write_snippet(
    os.path.join(this_dir, "snippet_teleport_annotated.deq"),
    extract_block(annotated_text, "GADGET", "Teleport"),
)
