name: qdk-ec-publish-$(BuildId)

# Manual trigger only for publishing pipeline
# To run: Queue manually and approve the release stage
trigger: none

pr: none

variables:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN_VERSION: "1.83"
  # Publishing configuration is managed via pipeline variables and/or variable groups.
  # Note: Rust crates and Python packages are published via ESRP (Enterprise Software Release Process)

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

parameters:
  - name: publishBinar
    displayName: 'Publish binar (Rust crate)'
    type: boolean
    default: false
  - name: publishPaulimer
    displayName: 'Publish paulimer (Rust crate)'
    type: boolean
    default: false
  - name: publishPauliverse
    displayName: 'Publish pauliverse (Rust crate)'
    type: boolean
    default: false
  - name: publishBinarPython
    displayName: 'Publish binar (Python package)'
    type: boolean
    default: false
  - name: publishPaulimerPython
    displayName: 'Publish paulimer (Python package)'
    type: boolean
    default: false
  - name: pythonVersions
    type: object
    default:
      - "3.9"
      - "3.10"
      - "3.11"
      - "3.12"
      - "3.13"
      - "3.14"
  - name: platforms
    type: object
    default:
      - name: linux
        poolName: "Azure-Pipelines-DevTools-EO"
        imageName: "ubuntu-latest"
        os: linux
      - name: macOS
        poolName: "Azure-Pipelines-DevTools-EO"
        imageName: "macOS-latest"
        os: macOS
      - name: windows
        poolName: "Azure-Pipelines-DevTools-EO"
        imageName: "windows-latest"
        os: windows

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: "Azure-Pipelines-DevTools-EO"
        image: windows-2022
        os: windows
    stages:
    - template: stages/build-stage.yml
      parameters:
        platforms: ${{ parameters.platforms }}
        pythonVersions: ${{ parameters.pythonVersions }}

    - template: stages/build-wheels-stage.yml
      parameters:
        platforms: ${{ parameters.platforms }}
        pythonVersions: ${{ parameters.pythonVersions }}

    - template: stages/approval-stage.yml

    - template: stages/publish-crates-stage.yml
      parameters:
        publishBinar: ${{ parameters.publishBinar }}
        publishPaulimer: ${{ parameters.publishPaulimer }}
        publishPauliverse: ${{ parameters.publishPauliverse }}

    - template: stages/publish-python-stage.yml
      parameters:
        publishBinarPython: ${{ parameters.publishBinarPython }}
        publishPaulimerPython: ${{ parameters.publishPaulimerPython }}
