name: qdk-ec-publish-$(BuildId)

# Manual trigger only for publishing pipeline
# To run: Queue manually and approve the release stage
trigger: none

pr: none

variables:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN_VERSION: "1.90"
  # Publishing configuration is managed via pipeline variables and/or variable groups.
  # Note: Rust crates and Python packages are published via ESRP (Enterprise Software Release Process)

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

parameters:
  - name: publishBinar
    displayName: 'Publish binar (Rust crate)'
    type: boolean
    default: false
  - name: publishPaulimer
    displayName: 'Publish paulimer (Rust crate)'
    type: boolean
    default: false
  - name: publishPauliverse
    displayName: 'Publish pauliverse (Rust crate)'
    type: boolean
    default: false
  - name: publishBinarPython
    displayName: 'Publish binar (Python package)'
    type: boolean
    default: false
  - name: publishPaulimerPython
    displayName: 'Publish paulimer (Python package)'
    type: boolean
    default: false
  - name: pythonVersions
    type: object
    default:
      - "3.9"
      - "3.10"
      - "3.11"
      - "3.12"
      - "3.13"
      - "3.14"
  - name: platforms
    type: object
    default:
      - name: linux_x86_64
        poolName: "Azure-Pipelines-DevTools-EO"
        imageName: "ubuntu-latest"
        os: linux
        arch: x86_64
      - name: linux_aarch64
        poolName: "Azure-Pipelines-DevTools-ARM64-EO"
        os: linux
        arch: aarch64
      - name: mac_x86_64
        poolName: "Azure Pipelines"
        imageName: "macOS-latest"
        os: macOS
        arch: x86_64
      - name: mac_aarch64
        poolName: "AcesShared"
        os: macOS
        arch: aarch64
      - name: windows_x86_64
        poolName: "Azure-Pipelines-DevTools-EO"
        imageName: "windows-latest"
        os: windows
        arch: x86_64

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: "Azure-Pipelines-DevTools-EO"
        image: windows-2022
        os: windows
    stages:
    - stage: build
      displayName: Build and Test
      jobs:
      - ${{ each platform in parameters.platforms }}:
        - ${{ each pythonVersion in parameters.pythonVersions }}:
          - job: ${{ platform.name }}_py${{ replace(pythonVersion, '.', '') }}
            ${{ if eq(platform.poolName, 'AcesShared') }}:
              pool:
                name: ${{ platform.poolName }}
                demands:
                - ImageOverride -equals ACES_VM_SharedPool_Sequoia
                os: ${{ platform.os }}
            ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
              pool:
                name: ${{ platform.poolName }}
                ${{ if platform.imageName }}:
                  image: ${{ platform.imageName }}
                os: ${{ platform.os }}
                hostArchitecture: Arm64
            ${{ else }}:
              pool:
                name: ${{ platform.poolName }}
                ${{ if platform.imageName }}:
                  image: ${{ platform.imageName }}
                os: ${{ platform.os }}
            variables:
              pythonVersion: ${{ pythonVersion }}
            timeoutInMinutes: 90
            steps:
            - task: RustInstaller@1
              inputs:
                rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
              displayName: Install Rust toolchain

            - script: rustup component add clippy rustfmt
              displayName: Install linting components

            - script: rustup --version && cargo --version && rustc --version
              displayName: Show toolchain details

            - script: cargo build --workspace --all-features
              displayName: Build workspace
              env:
                RUSTFLAGS: "-C target-cpu=native"

            - script: cargo clippy-all
              displayName: Check code style and best practices (clippy)

            - script: cargo fmt --check
              displayName: Check code formatting (rustfmt)

            - script: cargo bench --no-run
              displayName: Build benchmarks
              env:
                RUSTFLAGS: "-C target-cpu=native"

            - template: .ado/templates/build-python-bindings-steps.yaml@self

            - bash: |
                source qdk_env/bin/activate
                cargo test --workspace --release
              displayName: Run tests (Linux/Mac)
              condition: ne( variables['Agent.OS'], 'Windows_NT')
              env:
                RUSTFLAGS: "-C target-cpu=native"

            - script: |
                call qdk_env\Scripts\activate.bat
                cargo test --workspace --release
              displayName: Run tests (Windows)
              condition: eq( variables['Agent.OS'], 'Windows_NT')
              env:
                RUSTFLAGS: "-C target-cpu=native"

    - stage: build_python_wheels
      displayName: Build Python Wheels
      dependsOn: build
      condition: succeeded()
      jobs:
      - ${{ each platform in parameters.platforms }}:
        - ${{ each pythonVersion in parameters.pythonVersions }}:
          - job: Python_${{ platform.name }}_py${{ replace(pythonVersion, '.', '') }}_job
            ${{ if eq(platform.poolName, 'AcesShared') }}:
              pool:
                name: ${{ platform.poolName }}
                demands:
                - ImageOverride -equals ACES_VM_SharedPool_Sequoia
                os: ${{ platform.os }}
            ${{ elseif and(eq(platform.arch, 'aarch64'), eq(platform.os, 'linux')) }}:
              pool:
                name: ${{ platform.poolName }}
                ${{ if platform.imageName }}:
                  image: ${{ platform.imageName }}
                os: ${{ platform.os }}
                hostArchitecture: Arm64
            ${{ else }}:
              pool:
                name: ${{ platform.poolName }}
                ${{ if platform.imageName }}:
                  image: ${{ platform.imageName }}
                os: ${{ platform.os }}
            variables:
              pythonVersion: ${{ pythonVersion }}
            timeoutInMinutes: 60
            templateContext:
              outputs:
              - output: pipelineArtifact
                displayName: "Upload Python Artifacts Mac"
                condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
                targetPath: $(System.DefaultWorkingDirectory)/target/wheels
                artifactName: mac-${{ platform.arch }}-wheels-python${{ pythonVersion }}
              - output: pipelineArtifact
                displayName: "Upload Python Artifacts Win"
                condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
                targetPath: $(System.DefaultWorkingDirectory)/target/wheels
                artifactName: windows-${{ platform.arch }}-wheels-python${{ pythonVersion }}
              - output: pipelineArtifact
                displayName: "Upload Python Artifacts Linux"
                condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
                targetPath: $(System.DefaultWorkingDirectory)/target/wheels
                artifactName: linux-${{ platform.arch }}-wheels-python${{ pythonVersion }}
            steps:
            - task: UsePythonVersion@0
              displayName: Install Python
              inputs:
                versionSpec: "$(pythonVersion)"

            - task: RustInstaller@1
              inputs:
                rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
              displayName: Install Rust toolchain

            - bash: |
                python -m pip install --upgrade maturin
                mkdir -p target/wheels
                cd binar/bindings/python
                maturin build --release --out ../../../target/wheels
                cd ../../..
                cd paulimer/bindings/python
                maturin build --release --out ../../../target/wheels
              displayName: Build Python wheels (Linux/Mac)
              condition: ne( variables['Agent.OS'], 'Windows_NT')

            - script: |
                python -m pip install --upgrade maturin
                if not exist target\wheels mkdir target\wheels
                cd binar\bindings\python
                maturin build --release --out ..\..\..\target\wheels
                cd ..\..\..
                cd paulimer\bindings\python
                maturin build --release --out ..\..\..\target\wheels
              displayName: Build Python wheels (Windows)
              condition: eq( variables['Agent.OS'], 'Windows_NT')

            - bash: |
                ls -la target/wheels/
              displayName: List built wheels (Linux/Mac)
              condition: ne( variables['Agent.OS'], 'Windows_NT')

            - script: |
                dir target\wheels\
              displayName: List built wheels (Windows)
              condition: eq( variables['Agent.OS'], 'Windows_NT')

    - stage: approval
      displayName: Approval
      dependsOn: build_python_wheels
      condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
      jobs:
      - job: "Approval"
        pool: server
        timeoutInMinutes: 1440
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1440
          inputs:
            notifyUsers: ""
            instructions: "Please verify artifacts and approve the release"
            onTimeout: "reject"

    - stage: publish_crates
      displayName: Publish Rust Crates
      dependsOn: approval
      condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), or(eq(${{ parameters.publishBinar }}, true), eq(${{ parameters.publishPaulimer }}, true), eq(${{ parameters.publishPauliverse }}, true)))
      jobs:
      - job: "Publish_Crates"
        pool:
          name: "Azure-Pipelines-DevTools-EO"
          image: "ubuntu-latest"
          os: linux
        templateContext:
          type: releaseJob
          isProduction: true
        steps:
        - task: RustInstaller@1
          inputs:
            rustVersion: ms-prod-$(RUST_TOOLCHAIN_VERSION)
          displayName: Install Rust toolchain

        - script: |
            mkdir -p $(System.DefaultWorkingDirectory)/target/crates
          displayName: Create crates directory

        - script: |
            cd binar
            cargo package
            cp target/package/binar-*.crate $(System.DefaultWorkingDirectory)/target/crates/
            cd ..
          displayName: Package binar
          condition: eq(${{ parameters.publishBinar }}, true)
        
        - script: |
            cd paulimer
            cargo package
            cp target/package/paulimer-*.crate $(System.DefaultWorkingDirectory)/target/crates/
            cd ..
          displayName: Package paulimer
          condition: eq(${{ parameters.publishPaulimer }}, true)
        
        - script: |
            cd pauliverse
            cargo package
            cp target/package/pauliverse-*.crate $(System.DefaultWorkingDirectory)/target/crates/
            cd ..
          displayName: Package pauliverse
          condition: eq(${{ parameters.publishPauliverse }}, true)

        - script: |
            ls -la $(System.DefaultWorkingDirectory)/target/crates/
          displayName: List packaged crates

        - task: EsrpRelease@9
          condition: succeeded()
          displayName: Publish Rust crates to crates.io
          inputs:
            connectedservicename: "PME ESRP Azure Connection"
            usemanagedidentity: true
            keyvaultname: "quantum-esrp-kv"
            signcertname: ESRPCert
            clientid: "832c049d-cd07-4c1c-bfa5-c07250d190cb"
            contenttype: CratesIO
            domaintenantid: "975f013f-7f24-47e8-a7d3-abc4752bf346"
            folderlocation: "$(System.DefaultWorkingDirectory)/target/crates"
            waitforreleasecompletion: true
            owners: "adpaetzn@microsoft.com"
            approvers: "adpaetzn@microsoft.com"
            mainpublisher: ESRPRELPACMAN

    - stage: publish_python
      displayName: Publish Python Packages
      dependsOn: approval
      condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), or(eq(${{ parameters.publishBinarPython }}, true), eq(${{ parameters.publishPaulimerPython }}, true)))
      jobs:
      - job: "Publish_Python_Packages"
        pool:
          name: "Azure-Pipelines-DevTools-EO"
          image: "ubuntu-latest"
          os: linux
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          # Collect all platform/python version combinations
          - ${{ each platform in parameters.platforms }}:
            - ${{ each pythonVersion in parameters.pythonVersions }}:
              - ${{ if eq(platform.os, 'linux') }}:
                - input: pipelineArtifact
                  artifactName: linux-${{ platform.arch }}-wheels-python${{ pythonVersion }}
                  targetPath: $(System.DefaultWorkingDirectory)/artifacts/linux-${{ platform.arch }}-python${{ pythonVersion }}
              - ${{ if eq(platform.os, 'macOS') }}:
                - input: pipelineArtifact
                  artifactName: mac-${{ platform.arch }}-wheels-python${{ pythonVersion }}
                  targetPath: $(System.DefaultWorkingDirectory)/artifacts/mac-${{ platform.arch }}-python${{ pythonVersion }}
              - ${{ if eq(platform.os, 'windows') }}:
                - input: pipelineArtifact
                  artifactName: windows-${{ platform.arch }}-wheels-python${{ pythonVersion }}
                  targetPath: $(System.DefaultWorkingDirectory)/artifacts/windows-${{ platform.arch }}-python${{ pythonVersion }}
        steps:
        - script: |
            mkdir -p $(System.DefaultWorkingDirectory)/target/wheels
          displayName: Create wheels directory

        - script: |
            find $(System.DefaultWorkingDirectory)/artifacts -name "binar-*.whl" -exec cp {} $(System.DefaultWorkingDirectory)/target/wheels/ \;
          displayName: Collect binar wheels
          condition: eq(${{ parameters.publishBinarPython }}, true)

        - script: |
            find $(System.DefaultWorkingDirectory)/artifacts -name "paulimer-*.whl" -exec cp {} $(System.DefaultWorkingDirectory)/target/wheels/ \;
          displayName: Collect paulimer wheels
          condition: eq(${{ parameters.publishPaulimerPython }}, true)

        - script: |
            ls -la $(System.DefaultWorkingDirectory)/target/wheels
          displayName: List collected wheels

        - task: EsrpRelease@9
          condition: succeeded()
          displayName: Publish Py Packages
          inputs:
            connectedservicename: "PME ESRP Azure Connection"
            usemanagedidentity: true
            keyvaultname: "quantum-esrp-kv"
            signcertname: ESRPCert
            clientid: "832c049d-cd07-4c1c-bfa5-c07250d190cb"
            contenttype: PyPi
            domaintenantid: "975f013f-7f24-47e8-a7d3-abc4752bf346"
            folderlocation: "$(System.DefaultWorkingDirectory)/target/wheels"
            waitforreleasecompletion: true
            owners: "adpaetzn@microsoft.com"
            approvers: "adpaetzn@microsoft.com"
            mainpublisher: ESRPRELPACMAN
