name: qdk-ec-publish-$(BuildId)

# Manual trigger only for publishing pipeline
# To run: Queue manually and approve the release stage
trigger: none

pr: none

variables:
  - name: CARGO_TERM_COLOR
    value: always
  - name: RUST_TOOLCHAIN_VERSION
    value: "1.90"
  # Publishing configuration is managed via pipeline variables and/or variable groups.
  # Note: Rust crates and Python packages are published via ESRP (Enterprise Software Release Process)

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

parameters:
  - name: publishBinar
    displayName: 'Publish binar (Rust crate)'
    type: boolean
    default: false
  - name: publishPaulimer
    displayName: 'Publish paulimer (Rust crate)'
    type: boolean
    default: false
  - name: publishPauliverse
    displayName: 'Publish pauliverse (Rust crate)'
    type: boolean
    default: false
  - name: publishBinarPython
    displayName: 'Publish binar (Python package)'
    type: boolean
    default: false
  - name: publishPaulimerPython
    displayName: 'Publish paulimer (Python package)'
    type: boolean
    default: false
  - name: pythonVersions
    type: object
    default:
    - '3.9'
    - '3.10'
    - '3.11'
    - '3.12'
    - '3.13'
    - '3.14'
  - name: platforms
    type: object
    default:
      - name: linux_x86_64
        poolName: "Azure-Pipelines-DevTools-EO"
        imageName: "ubuntu-latest"
        os: linux
        arch: x86_64
      - name: linux_aarch64
        poolName: "Azure-Pipelines-DevTools-ARM64-EO"
        os: linux
        arch: aarch64
      - name: mac_x86_64
        poolName: "Azure Pipelines"
        imageName: "macOS-latest"
        os: macOS
        arch: x86_64
      - name: mac_aarch64
        poolName: "AcesShared"
        os: macOS
        arch: aarch64
      - name: windows_x86_64
        poolName: "Azure-Pipelines-DevTools-EO"
        imageName: "windows-latest"
        os: windows
        arch: x86_64

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: "Azure-Pipelines-DevTools-EO"
        image: windows-2022
        os: windows
    stages:
    - template: stages/build.yaml@self
      parameters:
        platforms: ${{ parameters.platforms }}
        pythonVersions: ${{ parameters.pythonVersions }}

    - template: stages/build_python_wheels.yaml@self
      parameters:
        platforms: ${{ parameters.platforms }}
        pythonVersions: ${{ parameters.pythonVersions }}

    - template: stages/approval.yaml@self

    - template: stages/publish_crates.yaml@self
      parameters:
        publishBinar: ${{ parameters.publishBinar }}
        publishPaulimer: ${{ parameters.publishPaulimer }}
        publishPauliverse: ${{ parameters.publishPauliverse }}

    - template: stages/publish_python.yaml@self
      parameters:
        platforms: ${{ parameters.platforms }}
        pythonVersions: ${{ parameters.pythonVersions }}
        publishBinarPython: ${{ parameters.publishBinarPython }}
        publishPaulimerPython: ${{ parameters.publishPaulimerPython }}
