"""Derive, verify, and emit the 6-qubit (1,1)-torus honeycomb Floquet code bundle.

The honeycomb Floquet code (Hastings-Haah, Quantum 5, 564) lives on a 3-regular,
3-edge-colored lattice. The smallest faithful torus is the (1,1) instance: 6
qubits, 9 two-body edge checks (3 per color), k=2 dynamically generated logical
qubits whose operators rotate with the instantaneous stabilizer group (ISG).

Each ISG is generated by two of that color's edges together with the two
conserved plaquettes X^{\\otimes 6} (stabilizer index 2) and Z^{\\otimes 6}
(index 3); the third edge is the product of the first two with a plaquette, so it
is a deterministic detector rather than a free generator. Pinning the plaquettes
to indices 2 and 3 in every ISG lets the round gadgets carry them forward by a
fixed index.

This derives the codes and a logical basis, checks the Pauli algebra and the
preservation of both logical qubits, and writes the single-file qodec bundle.

Run from an environment with ``qdk`` (for ``StabilizerCode`` and the audit) and
``paulimer`` on the path.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

import yaml

from paulimer import OutcomeCompleteSimulation, PauliGroup, SparsePauli

# No public qdk.ec export for these yet.
from qdk.ec._analysis.propagation.frames import FrameGroup, PauliFrame
from qdk.ec._analysis.propagation.pauli import Pauli
from qdk.ec._analysis.stabilizer_code import StabilizerCode

QUBITS = 6
ORDER = ("red", "green", "blue")
BASIS: dict[str, Literal["I", "X", "Y", "Z"]] = {"green": "Y", "red": "X", "blue": "Z"}
PREVIOUS = {"green": "red", "blue": "green", "red": "blue"}

# (1,1)-torus edges, relabeled to qubits 0..5, sorted within each color by the
# smaller endpoint so the stabilizer index matches the measurement order.
EDGES = {
    "green": [(0, 4), (1, 3), (2, 5)],  # YY
    "red": [(0, 1), (2, 3), (4, 5)],  # XX
    "blue": [(0, 2), (1, 5), (3, 4)],  # ZZ
}

X_ALL = Pauli({q: "X" for q in range(QUBITS)})
Z_ALL = Pauli({q: "Z" for q in range(QUBITS)})

# The plaquette index that the product of a color's three edges reproduces.
# `isg_stabilizers` orders each ISG as [edge, edge, X_ALL, Z_ALL], so X^6 is at
# index 2 and Z^6 at index 3: XX edges multiply to X^6; ZZ edges to Z^6; YY edges
# to Y^6 = -X^6 . Z^6. Invert the third green outcome to obtain zero check parity.
DETECTOR_PLAQUETTES = {"red": (2,), "blue": (3,), "green": (2, 3)}


def edge_pauli(color: str, pair: tuple[int, int]) -> Pauli:
    return Pauli({pair[0]: BASIS[color], pair[1]: BASIS[color]})


def color_paulis(color: str) -> list[Pauli]:
    return [edge_pauli(color, pair) for pair in EDGES[color]]


def isg_stabilizers(color: str) -> list[Pauli]:
    """Two color edges plus both conserved plaquettes (four independent generators)."""
    return color_paulis(color)[:2] + [X_ALL, Z_ALL]


def isg_code(color: str) -> StabilizerCode:
    return StabilizerCode(isg_stabilizers(color))


def logicals(color: str) -> tuple[list[Pauli], list[Pauli]]:
    basis = list(isg_code(color).logical_basis)
    return [basis[0], basis[2]], [basis[1], basis[3]]


# ── verification ─────────────────────────────────────────────────────────────


def _commutes(left: Pauli, right: Pauli) -> bool:
    overlap = set(left.support) & set(right.support)
    return sum(1 for q in overlap if left[q] != right[q]) % 2 == 0


def verify_algebra() -> None:
    for color in ORDER:
        code = isg_code(color)
        assert len(list(code.logical_basis)) == 2 * 2, color  # k = 2
        x_ops, z_ops = logicals(color)
        stabs = isg_stabilizers(color)
        for logical in x_ops + z_ops:
            for stab in stabs:
                assert _commutes(logical, stab), (color, logical, stab)
        for i in range(2):
            assert not _commutes(x_ops[i], z_ops[i]), (color, i)
            assert _commutes(x_ops[i], z_ops[1 - i]), (color, i)
        # the third edge is in the ISG (a detector, not an independent generator)
        third = color_paulis(color)[2]
        residual = (PauliGroup([third]) % PauliGroup(stabs)).generators[0]
        assert residual.weight == 0, (color, third, residual)
    for color in ORDER:
        for edge in color_paulis(color):
            assert _commutes(edge, X_ALL) and _commutes(edge, Z_ALL), (color, edge)


def verify_faithful(periods: int = 3) -> int:
    """Return the entangled (preserved-logical) count of a Choi period; expect 4."""
    aux = QUBITS
    sim = OutcomeCompleteSimulation(2 * QUBITS)
    for q in range(QUBITS):
        sim.measure(SparsePauli({q: "X", q + aux: "X"}))
        sim.measure(SparsePauli({q: "Z", q + aux: "Z"}))
    for _ in range(periods):
        for color in ("green", "blue", "red"):
            basis = BASIS[color]
            for a, b in EDGES[color]:
                sim.measure(SparsePauli({a: basis, b: basis}))
    choi = FrameGroup(PauliFrame(Pauli.from_dense(sim.clifford.image_z(q))) for q in range(2 * QUBITS))
    _, _, entangled = choi.partition(over=frozenset(range(QUBITS)))
    return len(entangled.generators)


# ── YAML emission ────────────────────────────────────────────────────────────


def pauli_str(pauli: Pauli) -> str:
    return " ".join(f"{pauli[q]}_{q}" for q in sorted(pauli.support))


def measure_gate(basis: str) -> str:
    """Native two-body Pauli-parity measurement mnemonic (``MXX``/``MYY``/``MZZ``)."""
    return f"M{basis}{basis}"


def z_pairs(pauli: Pauli) -> list[tuple[int, int]]:
    """Split an all-Z, even-weight operator into disjoint qubit pairs.

    The red logical Z operators are products of Z's, so each is read out as a
    product of two-body ``MZZ`` measurements on these pairs.
    """
    support = sorted(pauli.support)
    assert len(support) % 2 == 0 and all(str(pauli[q]) == "Z" for q in support), pauli
    return [(support[i], support[i + 1]) for i in range(0, len(support), 2)]


def code_block(color: str) -> dict[str, Any]:
    x_ops, z_ops = logicals(color)
    pair = BASIS[color] * 2
    return {
        f"isg_{color}.code.yaml": {
            "name": f"isg_{color}",
            "description": (
                f"Instantaneous stabilizer group after the {color} round: two {color} "
                f"edge checks ({pair}, stabilizers 0-1) plus the two conserved plaquettes "
                f"X^6 (2) and Z^6 (3). The third {color} edge is their product (a "
                "detector). k=2 dynamically generated logical qubits rotate with the ISG."
            ),
            "stabilizers": [pauli_str(stabilizer) for stabilizer in isg_stabilizers(color)],
            "x": [pauli_str(operator) for operator in x_ops],
            "z": [pauli_str(operator) for operator in z_ops],
        }
    }


def round_circuit(color: str) -> dict[str, Any]:
    if color == "green":
        calls = [
            {"MYY_NEG" if index == 2 else "MYY": [first, second]} for index, (first, second) in enumerate(EDGES[color])
        ]
        return {"source": calls}
    gate = measure_gate(BASIS[color])
    return {"format": "stim", "source": "\n".join(f"{gate} {first} {second}" for first, second in EDGES[color])}


def round_frames(color: str) -> dict[str, list[str | int]]:
    return {
        "red": {"out[0].x[0]": ["circuit.readouts[1]"]},
        "green": {
            "out[0].z[0]": ["circuit.readouts[0]", 1],
            "out[0].z[1]": ["circuit.readouts[0]", "circuit.readouts[1]", 1],
        },
        "blue": {
            "out[0].x[0]": ["circuit.readouts[0]"],
            "out[0].z[0]": ["circuit.readouts[0]"],
            "out[0].x[1]": ["circuit.readouts[0]", "circuit.readouts[1]", 1],
            "out[0].z[1]": ["circuit.readouts[1]", 1],
        },
    }[color]


def round_gadget(color: str) -> dict[str, Any]:
    checks = [
        ["circuit.readouts[0]", "out[0].stabilizers[0]"],
        ["circuit.readouts[1]", "out[0].stabilizers[1]"],
        ["in[0].stabilizers[2]", "out[0].stabilizers[2]"],
        ["in[0].stabilizers[3]", "out[0].stabilizers[3]"],
        [f"circuit.readouts[{index}]" for index in range(3)]
        + [f"in[0].stabilizers[{index}]" for index in DETECTOR_PLAQUETTES[color]],
    ]
    return {
        f"round_{color}.gadget.yaml": {
            "circuit": round_circuit(color),
            "in": [{f"isg_{PREVIOUS[color]}": list(range(QUBITS))}],
            "out": [{f"isg_{color}": list(range(QUBITS))}],
            "frames": round_frames(color),
            "checks": checks,
        }
    }


def prepare_gadget() -> dict[str, Any]:
    source = ["R 0 1 2 3 4 5"]
    source += [f"MXX {first} {second}" for first, second in EDGES["red"]]
    checks = [
        ["circuit.readouts[0]", "out[0].stabilizers[0]"],
        ["circuit.readouts[1]", "out[0].stabilizers[1]"],
        [
            "circuit.readouts[0]",
            "circuit.readouts[1]",
            "circuit.readouts[2]",
            "out[0].stabilizers[2]",
        ],
        ["out[0].stabilizers[3]"],
    ]
    return {
        "prepare_red_all.gadget.yaml": {
            "circuit": {"format": "stim", "source": "\n".join(source)},
            "out": [{"isg_red": list(range(QUBITS))}],
            "checks": checks,
        }
    }


def measure_gadget() -> dict[str, Any]:
    _, z_ops = logicals("red")
    pairs: list[tuple[int, int]] = []
    for operator in z_ops:
        for pair in z_pairs(operator):
            if pair not in pairs:
                pairs.append(pair)
    source = [f"MZZ {first} {second}" for first, second in pairs]
    readouts = []
    for index, operator in enumerate(z_ops):
        atoms = [f"circuit.readouts[{pairs.index(pair)}]" for pair in z_pairs(operator)]
        atoms.append(f"in[0].z[{index}]")
        readouts.append(atoms)
    return {
        "measure_red_all.gadget.yaml": {
            "circuit": {"format": "stim", "source": "\n".join(source)},
            "in": [{"isg_red": list(range(QUBITS))}],
            "readouts": readouts,
        }
    }


HEADER = """\
# Honeycomb Floquet code - single-file qodec bundle (generated).
#
# A measurement-only code on the honeycomb lattice (Hastings-Haah, Quantum 5, 564,
# 2021). Qubits on vertices; the three edge colors carry two-qubit checks
# red=XX, green=YY, blue=ZZ; a period-3 schedule measures all red, then green, then
# blue checks. The INSTANTANEOUS STABILIZER GROUP rotates each round: its
# generators are two of that color's edge checks plus the two conserved plaquettes
# (X^6 and Z^6, the Floquet detectors). The k=2 logical operators rotate too.
#
# qodec models the rotating ISG as THREE codes (isg_red/green/blue) with the rounds
# as code-switching gadgets (in: previous phase, out: next phase). The same 6 physical qubits are
# described by three different stabilizer groups; this is the catalog's sharpest
# test of qodec's otherwise-static "one code per block" assumption.
#
# Smallest FAITHFUL instance: the honeycomb on the (1,1) torus - 6 qubits, 3 edges
# per color, k=2 logical qubits. (The (1,1) torus is the minimal size whose period
# preserves the logical information; verified by generate_honeycomb.py.)
#
# Reference: M. B. Hastings, J. Haah, "Dynamically Generated Logical Qubits",
# Quantum 5, 564 (2021); A. Kitaev, Ann. Phys. 321, 2 (2006) (the honeycomb model).
"""

MANIFEST = """\
qodec.yaml:
  name: honeycomb
  description: >-
    The honeycomb Floquet code on the (1,1) torus: a period-3 schedule of XX/YY/ZZ
    edge measurements whose instantaneous stabilizer group rotates each round.
    Modeled as three ISG codes with code-switching round gadgets.
  layers:
    - instruction_set: honeycomb.isa.yaml
      codes:
        isg_red: isg_red.code.yaml
        isg_green: isg_green.code.yaml
        isg_blue: isg_blue.code.yaml
      gadgets:
        prepare_red_all: prepare_red_all.gadget.yaml
        round_green: round_green.gadget.yaml
        round_blue: round_blue.gadget.yaml
        round_red: round_red.gadget.yaml
        measure_red_all: measure_red_all.gadget.yaml
    - instruction_set: ../stim.isa.yaml
"""

HONEYCOMB_ISA = """\
honeycomb.isa.yaml:
  name: honeycomb
  description: >-
    The Floquet schedule. A block is the honeycomb patch (k=2 logical qubits); its
    three block types are the three ISG phases. Each round measures one color's
    edge checks and advances the ISG, applying the per-round logical Clifford that
    rotates the instantaneous logical operators; the three rounds compose to the
    e<->m exchange automorphism over one period.
  blocks: {isg_red: 2, isg_green: 2, isg_blue: 2}
  instructions:
    - mnemonic: prepare_red_all
      description: >-
        Prepare the patch projected into the red ISG. The reset+projection
        circuit fixes the logical Z operators (the realization stabilizes Z_0,
        Z_1); the period's e/m rotation carries them to X across the schedule.
      out: [isg_red]
      action: [stabilize: [Z_0, Z_1]]
    - mnemonic: round_green
      description: Measure the green (YY) checks; advance isg_red -> isg_green.
      in: [isg_red]
      out: [isg_green]
      action: [clifford: {Z_0: Y_0 X_1, Z_1: X_0 Z_1}]
    - mnemonic: round_blue
      description: Measure the blue (ZZ) checks; advance isg_green -> isg_blue.
      in: [isg_green]
      out: [isg_blue]
      action: [clifford: {X_0: Z_0 Z_1, X_1: Z_1, Z_0: Y_0, Z_1: Y_0 Y_1}]
    - mnemonic: round_red
      description: Measure the red (XX) checks; advance isg_blue -> isg_red.
      in: [isg_blue]
      out: [isg_red]
      action: [clifford: {X_0: X_1, X_1: X_0 X_1, Z_0: Z_0 Z_1, Z_1: Z_0}]
    - mnemonic: measure_red_all
      description: Destructive readout of the two logical Z observables (red ISG).
      in: [isg_red]
      action: [observe: [Z_0, Z_1]]
"""


def bundle() -> str:
    documents = [
        yaml.safe_load(MANIFEST),
        yaml.safe_load(HONEYCOMB_ISA),
        code_block("red"),
        code_block("green"),
        code_block("blue"),
        prepare_gadget(),
        round_gadget("red"),
        round_gadget("green"),
        round_gadget("blue"),
        measure_gadget(),
    ]
    return HEADER + yaml.safe_dump_all(documents, sort_keys=False, allow_unicode=True)


def main() -> None:
    verify_algebra()
    entangled = verify_faithful()
    assert entangled == 4, f"period preserves {entangled // 2} logicals, expected 2"
    print(f"algebra OK; period preserves k={entangled // 2} logicals (entangled={entangled})")
    path = Path(__file__).with_name("honeycomb.qodec.yaml")
    path.write_text(bundle(), encoding="utf-8")
    print(f"wrote {path}")
    verify_audit(path)


def verify_audit(path: Path) -> None:
    """Require the emitted bundle to pass every audit check without warnings."""
    import qodec
    import qdk.ec as ec

    report = ec.audit(qodec.Qodec.load(str(path)), promote_warnings=True)
    assert report.ok, str(report)
    print("audit OK; the bundle is clean")


if __name__ == "__main__":
    main()
